import type { ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import {
  Handshake,
  Zap,
  BadgePercent,
  Banknote,
  Bell,
  BellRing,
  Building2,
  CalendarClock,
  ChartColumn,
  ClipboardList,
  CloudDownload,
  Coins,
  CreditCard,
  FileText,
  Gauge,
  Gift,
  Globe,
  Hammer,
  HandCoins,
  HeartPulse,
  HardDriveDownload,
  History,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Lock,
  MapPinned,
  MessageSquare,
  MessagesSquare,
  MonitorSmartphone,
  Network,
  Package,
  Palette,
  Receipt,
  Router,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  Smartphone,
  Store,
  Ticket,
  TrendingUp,
  Users,
  Wallet,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
} from "lucide-react";
import type { NavIcon } from "@/lib/navigation";
import { ICON_STROKE } from "@/components/icons";

/** Each menu entry's icon, from the Lucide set, one per destination so the menu scans at a glance. */
const GLYPHS: Record<NavIcon, LucideIcon> = {
  "badge-percent": BadgePercent,
  "banknote": Banknote,
  "bell": Bell,
  "bell-ring": BellRing,
  "building": Building2,
  "calendar-clock": CalendarClock,
  "chart": ChartColumn,
  "clipboard": ClipboardList,
  "cloud-download": CloudDownload,
  "coins": Coins,
  "credit-card": CreditCard,
  "dashboard": LayoutDashboard,
  "file-text": FileText,
  "gauge": Gauge,
  "handshake": Handshake,
  "zap": Zap,
  "gift": Gift,
  "globe": Globe,
  "hand-coins": HandCoins,
  "hard-drive": HardDriveDownload,
  "hard-hat": Hammer,
  "heart-pulse": HeartPulse,
  "history": History,
  "key": KeyRound,
  "landmark": Landmark,
  "layers": Layers,
  "lifebuoy": LifeBuoy,
  "lock": Lock,
  "map": MapPinned,
  "message": MessageSquare,
  "messages": MessagesSquare,
  "monitor": MonitorSmartphone,
  "network": Network,
  "package": Package,
  "palette": Palette,
  "receipt": Receipt,
  "router": Router,
  "scale": Scale,
  "scroll": ScrollText,
  "settings": Settings,
  "shield": ShieldCheck,
  "smartphone": Smartphone,
  "store": Store,
  "ticket": Ticket,
  "trending-up": TrendingUp,
  "users": Users,
  "wallet": Wallet,
  "webhook": Webhook,
  "wifi": Wifi,
  "workflow": Workflow,
  "wrench": Wrench,
};

/** Renders a navigation catalog icon name (lib/navigation.ts keeps the catalog React-free). */
export function NavIconGlyph({ name, size = 18 }: { name: NavIcon; size?: number }): ReactNode {
  const Glyph = GLYPHS[name] ?? LayoutDashboard;
  return <Glyph size={size} strokeWidth={ICON_STROKE} aria-hidden="true" />;
}
