import { prisma } from "@mashupkgrid/database";
import { sendInvoiceEmailJobSchema, type AutomationSummary } from "@mashupkgrid/shared";
import { sendEmail } from "../lib/email.js";

/**
 * The invoice itself, in the customer's inbox, the moment it exists.
 *
 * Renewal invoices are generated by the billing cycle with nobody watching; until now the first
 * a customer heard of one was the "due soon" reminder days later. This sends every newly issued
 * invoice — scheduled every few minutes for the ones the cycle creates, and on demand for a
 * staff "Email invoice" click. `Invoice.emailedAt` is what stops the same invoice going twice.
 */

type InvoiceForEmail = NonNullable<Awaited<ReturnType<typeof loadInvoice>>>;

async function loadInvoice(invoiceId: string) {
  return prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      items: true,
      customer: { select: { fullName: true, email: true, customerNumber: true } },
      tenant: { select: { name: true, currency: true } },
    },
  });
}

function money(minor: number, currency: string): string {
  return `${currency} ${(minor / 100).toLocaleString("en-KE", { minimumFractionDigits: 2 })}`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
}

export function buildInvoiceEmail(invoice: InvoiceForEmail): { subject: string; text: string; html: string } {
  const due = invoice.dueDate.toLocaleDateString("en-KE", { year: "numeric", month: "long", day: "numeric" });
  const owed = invoice.totalMinor - invoice.amountPaidMinor;
  const isPaid = owed <= 0;
  const subject = isPaid
    ? `Invoice ${invoice.invoiceNumber} from ${invoice.tenant.name} — paid`
    : `Invoice ${invoice.invoiceNumber} from ${invoice.tenant.name} — ${money(owed, invoice.currency)} due ${due}`;

  const lines = invoice.items.map((item) => `${item.description} × ${item.quantity}: ${money(item.totalMinor, invoice.currency)}`);
  const text = [
    `Hi ${invoice.customer.fullName},`,
    "",
    `Here is your invoice ${invoice.invoiceNumber} from ${invoice.tenant.name}.`,
    "",
    ...lines,
    "",
    `Total: ${money(invoice.totalMinor, invoice.currency)}`,
    ...(invoice.amountPaidMinor > 0 ? [`Paid so far: ${money(invoice.amountPaidMinor, invoice.currency)}`] : []),
    isPaid ? "This invoice is fully paid — thank you." : `Amount due: ${money(owed, invoice.currency)} by ${due}.`,
    "",
    ...(isPaid
      ? []
      : [
          `To pay, use your usual method and quote ${invoice.invoiceNumber} (or your account number ${invoice.customer.customerNumber}) as the reference. Paying before the due date keeps your service uninterrupted.`,
          "",
        ]),
    invoice.tenant.name,
  ].join("\n");

  const rows = invoice.items
    .map(
      (item) =>
        `<tr><td style="padding:6px 0;">${escapeHtml(item.description)}</td><td style="padding:6px 0;text-align:center;">${item.quantity}</td><td style="padding:6px 0;text-align:right;">${money(item.totalMinor, invoice.currency)}</td></tr>`
    )
    .join("");
  const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1e293b;background:#fff;border:1px solid #e2e8f0;border-radius:8px;">
      <p style="margin:0 0 4px;font-size:13px;color:#64748b;">${escapeHtml(invoice.tenant.name)}</p>
      <h2 style="margin:0 0 16px;font-size:20px;color:#0f172a;">Invoice ${escapeHtml(invoice.invoiceNumber)}</h2>
      <p style="font-size:15px;line-height:1.5;">Hi ${escapeHtml(invoice.customer.fullName)},</p>
      <table style="width:100%;border-collapse:collapse;font-size:14px;margin:16px 0;">
        <thead><tr style="color:#64748b;font-size:12px;text-transform:uppercase;"><th style="text-align:left;padding:6px 0;border-bottom:1px solid #e2e8f0;">Item</th><th style="text-align:center;padding:6px 0;border-bottom:1px solid #e2e8f0;">Qty</th><th style="text-align:right;padding:6px 0;border-bottom:1px solid #e2e8f0;">Amount</th></tr></thead>
        <tbody>${rows}</tbody>
        <tfoot>
          <tr><td colspan="2" style="padding:8px 0;border-top:1px solid #e2e8f0;">Total</td><td style="padding:8px 0;border-top:1px solid #e2e8f0;text-align:right;">${money(invoice.totalMinor, invoice.currency)}</td></tr>
          ${invoice.amountPaidMinor > 0 ? `<tr><td colspan="2" style="padding:4px 0;color:#64748b;">Paid so far</td><td style="padding:4px 0;text-align:right;color:#64748b;">${money(invoice.amountPaidMinor, invoice.currency)}</td></tr>` : ""}
          <tr><td colspan="2" style="padding:8px 0;font-weight:600;">${isPaid ? "Balance" : "Amount due"}</td><td style="padding:8px 0;text-align:right;font-weight:600;">${money(Math.max(owed, 0), invoice.currency)}</td></tr>
        </tfoot>
      </table>
      ${
        isPaid
          ? `<p style="font-size:15px;">This invoice is fully paid — thank you.</p>`
          : `<p style="font-size:15px;line-height:1.5;">Please pay <strong>${money(owed, invoice.currency)}</strong> by <strong>${escapeHtml(due)}</strong>. Use your usual method and quote <strong>${escapeHtml(invoice.invoiceNumber)}</strong> (or your account number ${escapeHtml(invoice.customer.customerNumber)}) as the reference. Paying before the due date keeps your service uninterrupted.</p>`
      }
      <p style="font-size:13px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:16px;margin-top:24px;">Sent by ${escapeHtml(invoice.tenant.name)} · reply to this email if anything looks wrong.</p>
    </div>`;
  return { subject, text, html };
}

/** Sends one invoice. Returns why it was not sent, or null on success. */
export async function emailInvoice(invoiceId: string, tenantId?: string): Promise<"no-such-invoice" | "no-email" | null> {
  const invoice = await loadInvoice(invoiceId);
  if (!invoice || (tenantId && invoice.tenantId !== tenantId)) return "no-such-invoice";
  if (!invoice.customer.email) return "no-email";
  await sendEmail({ to: invoice.customer.email, ...buildInvoiceEmail(invoice) });
  await prisma.invoice.update({ where: { id: invoice.id }, data: { emailedAt: new Date() } });
  return null;
}

export async function handleSendInvoiceEmail(payload: unknown): Promise<void> {
  const data = sendInvoiceEmailJobSchema.parse(payload);
  const skipped = await emailInvoice(data.invoiceId, data.tenantId);
  if (skipped) console.warn(`[invoices] invoice ${data.invoiceId} not emailed: ${skipped}`);
}

/**
 * Scheduled: every invoice issued in the last week that has not been emailed. The window keeps
 * a freshly configured mail transport from blasting months of history at customers, and a
 * customer with no email address is counted rather than retried forever.
 */
export async function handleSendPendingInvoiceEmails(): Promise<AutomationSummary> {
  const since = new Date(Date.now() - 7 * 24 * 60 * 60_000);
  const pending = await prisma.invoice.findMany({
    where: { emailedAt: null, status: { in: ["PENDING", "PARTIALLY_PAID", "OVERDUE"] }, issuedAt: { gte: since } },
    select: { id: true, customer: { select: { email: true } } },
    take: 200,
  });
  let sent = 0;
  let noEmail = 0;
  for (const row of pending) {
    if (!row.customer.email) {
      noEmail += 1;
      continue;
    }
    try {
      if ((await emailInvoice(row.id)) === null) sent += 1;
    } catch (err) {
      console.error(`[invoices] could not email invoice ${row.id}`, err);
    }
  }
  console.log(`[invoices] send-pending-invoice-emails: sent=${sent} noEmail=${noEmail}`);
  return { sent, noEmail };
}
