/**
 * Swahili for the dashboard pages that use tr(). Keys are the exact English text on the page;
 * a phrase missing here simply shows in English.
 */
export const SW: Record<string, string> = {
  "+ role": "+ jukumu",
  "0 turns the early reminder off.": "0 huzima ukumbusho wa mapema.",
  "A courtesy reminder while there is still time to pay.": "Ukumbusho wa heshima wakati bado kuna muda wa kulipa.",
  "A subdomain of a domain you own — not the bare platform domain.": "Kikoa kidogo cha kikoa unachomiliki, si kikoa cha jukwaa chenyewe.",
  "AI assistant": "Msaidizi wa AI",
  "API key": "Ufunguo wa API",
  "API tokens": "Tokeni za API",
  "API tokens for external clients, and webhooks for outbound event delivery.": "Tokeni za API kwa programu za nje, na webhooks za kutuma matukio nje.",
  "Account": "Akaunti",
  "Action": "Kitendo",
  "Actions": "Vitendo",
  "Active": "Hai",
  "Active Services": "Huduma Hai",
  "Active Subscribers": "Wateja Hai",
  "Active internet access": "Intaneti inayofanya kazi",
  "Add a colleague and give them a role that matches their job.": "Ongeza mwenzako na umpe jukumu linalolingana na kazi yake.",
  "Add a role": "Ongeza jukumu",
  "Add customer": "Ongeza mteja",
  "Add package": "Ongeza kifurushi",
  "Add time": "Ongeza muda",
  "Add your first package": "Ongeza kifurushi chako cha kwanza",
  "Address": "Anwani",
  "All Time": "Muda Wote",
  "All branches": "Matawi yote",
  "All vouchers": "Vocha zote",
  "Already done:": "Tayari imefanyika:",
  "Amount": "Kiasi",
  "Amount (KES)": "Kiasi (KES)",
  "Analytics": "Takwimu",
  "Anthropic API key": "Ufunguo wa API wa Anthropic",
  "Apply": "Tumia",
  "Apply payment to an invoice": "Weka malipo kwenye ankara",
  "Apply to invoice": "Weka kwenye ankara",
  "Assigned": "Aliyepewa",
  "At least 10 characters, with a letter and a digit or symbol.": "Angalau herufi 10, zikiwemo herufi na tarakimu au alama.",
  "Attempted": "Ilijaribiwa",
  "Automation": "Otomatiki",
  "Average Spend / User": "Wastani wa Matumizi / Mtumiaji",
  "Average lifetime spend": "Wastani wa matumizi yote",
  "Average per subscriber": "Wastani kwa kila mteja",
  "Average spend in period": "Wastani wa matumizi katika kipindi",
  "Avg Spend / Client": "Wastani / Mteja",
  "Awaiting approval": "Inasubiri idhini",
  "Bandwidth Usage": "Matumizi ya Data",
  "Bandwidth telemetry recorded across your routers.": "Takwimu za data zilizorekodiwa kwenye ruta zako zote.",
  "Based on": "Kulingana na",
  "Before the due date": "Kabla ya tarehe ya mwisho",
  "Billing Frequency": "Mzunguko wa Malipo",
  "Block sharing over a phone hotspot": "Zuia kushiriki kupitia hotspot ya simu",
  "Bot Test": "Jaribio la Bot",
  "Branch": "Tawi",
  "Branch name": "Jina la tawi",
  "Branches": "Matawi",
  "Branding and contact": "Chapa na mawasiliano",
  "Cancel": "Ghairi",
  "Captive Portal Studio": "Studio ya Ukurasa wa Kuingia",
  "Checked": "Imekaguliwa",
  "Choose a role…": "Chagua jukumu…",
  "Client": "Mteja",
  "Client Directory & Spend History": "Orodha ya Wateja na Historia ya Matumizi",
  "Client Name": "Jina la Mteja",
  "Clients & Spends": "Wateja na Matumizi",
  "Code": "Msimbo",
  "Collections, settlements and reconciliation": "Makusanyo, malipo na upatanisho",
  "Completed payments, in your timezone": "Malipo yaliyokamilika, kwa saa za eneo lako",
  "Configure DNS": "Sanidi DNS",
  "Confirm new password": "Thibitisha nenosiri jipya",
  "Copy": "Nakili",
  "Create Broadband Plan": "Unda Mpango wa Intaneti",
  "Create your first bandwidth subscription plan above.": "Unda mpango wako wa kwanza wa intaneti hapo juu.",
  "Cumulative customer LTV": "Jumla ya thamani ya wateja",
  "Current Plan": "Mpango wa Sasa",
  "Current password": "Nenosiri la sasa",
  "Custom Domain": "Kikoa Maalum",
  "Custom Range": "Kipindi Maalum",
  "Custom limits (no package)": "Mipaka maalum (bila kifurushi)",
  "Customer": "Mteja",
  "Customer phone, e.g. 254712345678": "Simu ya mteja, mf. 254712345678",
  "Customers": "Wateja",
  "Customers at risk": "Wateja walio hatarini",
  "Customers can tap to call it.": "Wateja wanaweza kugusa kupiga simu.",
  "Customers see these on the Wi-Fi sign-in page and pay for them with M-Pesa.": "Wateja huona hivi kwenye ukurasa wa kuingia Wi-Fi na hulipa kwa M-Pesa.",
  "Custom…": "Maalum…",
  "Dashboard colours": "Rangi za dashibodi",
  "Data": "Data",
  "Data limit (MB)": "Kikomo cha data (MB)",
  "Data used per day": "Data iliyotumika kwa siku",
  "Date & Time": "Tarehe na Saa",
  "Days before due date": "Siku kabla ya tarehe ya mwisho",
  "Delete": "Futa",
  "Describe the packages you want in plain words, and it creates or edits them for you.": "Eleza vifurushi unavyotaka kwa maneno ya kawaida, nao utaviunda au kuvihariri.",
  "Description (optional)": "Maelezo (si lazima)",
  "Design": "Muundo",
  "Detailed payment records with receipt numbers, client details, and M-Pesa references.": "Rekodi kamili za malipo zenye namba za risiti, maelezo ya mteja na kumbukumbu za M-Pesa.",
  "Developer": "Msanidi",
  "Devices": "Vifaa",
  "Devices per voucher": "Vifaa kwa kila vocha",
  "Dismiss": "Funga",
  "Domain": "Kikoa",
  "Domain Management": "Usimamizi wa Kikoa",
  "Download (Mbps)": "Kupakua (Mbps)",
  "Download (Rx)": "Kupakua (Rx)",
  "Download Speed (Kbps)": "Kasi ya Kupakua (Kbps)",
  "Download and upload": "Kupakua na kupakia",
  "Download and upload across all your routers.": "Kupakua na kupakia kwenye ruta zako zote.",
  "Download speed (Mbps)": "Kasi ya kupakua (Mbps)",
  "Downloaded": "Iliyopakuliwa",
  "Edit": "Hariri",
  "Email": "Barua pepe",
  "Email body": "Maandishi ya barua pepe",
  "Email subject": "Kichwa cha barua pepe",
  "Embed a Tawk.to chat widget for staff and/or hotspot customers.": "Weka kisanduku cha gumzo cha Tawk.to kwa wafanyakazi na/au wateja wa hotspot.",
  "Enabled": "Imewashwa",
  "Endpoint URL": "URL ya kupokea",
  "Enter this code on your phone": "Weka msimbo huu kwenye simu yako",
  "Event": "Tukio",
  "Events": "Matukio",
  "Every active customer is paid up and paying regularly.": "Kila mteja hai amelipa na analipa mara kwa mara.",
  "Every completed payment is on an invoice. Nothing to do here.": "Kila malipo yaliyokamilika yako kwenye ankara. Hakuna la kufanya hapa.",
  "Every hotspot and PPPoE session, with the customer and their last payment behind it. Updates every 20 seconds.": "Kila kipindi cha hotspot na PPPoE, pamoja na mteja na malipo yake ya mwisho. Husasishwa kila sekunde 20.",
  "Everyone who bought a package on your hotspot portal, and how much they've used.": "Kila aliyenunua kifurushi kwenye hotspot yako, na kiasi alichotumia.",
  "Everything is matched": "Kila kitu kimelinganishwa",
  "Expires": "Inaisha",
  "Export CSV": "Hamisha CSV",
  "Export Clients CSV": "Hamisha Wateja CSV",
  "FUP Status": "Hali ya FUP",
  "Failing": "Inashindwa",
  "Fast, reliable Wi-Fi": "Wi-Fi ya kasi na ya kuaminika",
  "Final notice": "Ilani ya mwisho",
  "Find a code": "Tafuta msimbo",
  "From": "Kuanzia",
  "Full access (same permissions as your account)": "Ruhusa kamili (sawa na akaunti yako)",
  "Gross completed payments": "Jumla ya malipo yaliyokamilika",
  "Growth, what sells, when customers pay, and who is at risk of leaving.": "Ukuaji, kinachouzika, wateja hulipa lini, na nani yuko hatarini kuondoka.",
  "Hardware orders": "Maagizo ya vifaa",
  "Heading": "Kichwa",
  "Highlight on the portal": "Angazia kwenye ukurasa",
  "Home and business lines": "Laini za nyumbani na biashara",
  "Home branch (optional)": "Tawi la nyumbani (si lazima)",
  "Home internet sales number": "Namba ya mauzo ya intaneti ya nyumbani",
  "Hotspot": "Hotspot",
  "Hotspot Vouchers": "Vocha za Hotspot",
  "Hotspot captive portal (customer-facing)": "Ukurasa wa kuingia hotspot (kwa wateja)",
  "Hotspot online": "Hotspot mtandaoni",
  "Hotspot sections": "Sehemu za hotspot",
  "Hours a new ticket may wait for its first reply before it shows as overdue on the Tickets page.": "Saa ambazo tiketi mpya inaweza kusubiri jibu la kwanza kabla ya kuonekana imechelewa kwenye ukurasa wa Tiketi.",
  "How many": "Ngapi",
  "How the sign-in page looks. MashupHost Clean loads fastest on phones.": "Jinsi ukurasa wa kuingia unavyoonekana. MashupHost Clean hufunguka haraka zaidi kwenye simu.",
  "ISPs": "Watoa huduma",
  "ISPs on the platform": "Watoa huduma kwenye jukwaa",
  "If you run in one area only, you do not need any.": "Ukifanya kazi eneo moja tu, huhitaji tawi lolote.",
  "Installation fee": "Ada ya ufungaji",
  "Internal note (not visible to the customer)": "Dokezo la ndani (mteja haoni)",
  "Invoice number, customer name or phone": "Namba ya ankara, jina la mteja au simu",
  "Joined This Month": "Walijiunga Mwezi Huu",
  "Joined This Week": "Walijiunga Wiki Hii",
  "Joined Today": "Walijiunga Leo",
  "Joined When": "Alijiunga Lini",
  "Joined:": "Alijiunga:",
  "Key name": "Jina la ufunguo",
  "Label": "Lebo",
  "Last 14 Days": "Siku 14 Zilizopita",
  "Last 30 Days": "Siku 30 Zilizopita",
  "Last 7 Days": "Siku 7 Zilizopita",
  "Last payment": "Malipo ya mwisho",
  "Last sign-in": "Kuingia mara ya mwisho",
  "Lasts": "Hudumu",
  "Lasts (minutes)": "Hudumu (dakika)",
  "Latest Receipt": "Risiti ya Karibuni",
  "Lets you manage hotspot packages by describing changes in plain language, from the Hotspot Vouchers page.": "Hukuwezesha kusimamia vifurushi vya hotspot kwa kueleza mabadiliko kwa lugha ya kawaida, kutoka ukurasa wa Vocha za Hotspot.",
  "Link a Device": "Unganisha Kifaa",
  "Link a router": "Unganisha ruta",
  "Link router": "Unganisha ruta",
  "Link with phone number": "Unganisha kwa namba ya simu",
  "Link your first MikroTik": "Unganisha MikroTik yako ya kwanza",
  "Link your own WhatsApp number to send vouchers and answer customers automatically.": "Unganisha namba yako ya WhatsApp ili kutuma vocha na kujibu wateja kiotomatiki.",
  "Linked Devices": "Vifaa Vilivyounganishwa",
  "Linked number": "Namba iliyounganishwa",
  "Linking a router generates a setup script for it, with its own RADIUS secret.": "Kuunganisha ruta hutengeneza hati ya usanidi wake, yenye siri yake ya RADIUS.",
  "Live chat": "Gumzo la moja kwa moja",
  "Loading client tracker...": "Inapakia wateja...",
  "Loading daily telemetry...": "Inapakia takwimu za kila siku...",
  "Loading domains...": "Inapakia vikoa...",
  "Loading packages...": "Inapakia vifurushi...",
  "Loading packages…": "Inapakia vifurushi…",
  "Loading sales…": "Inapakia mauzo…",
  "Loading subscription...": "Inapakia usajili...",
  "Loading ticket...": "Inapakia tiketi...",
  "Loading tickets...": "Inapakia tiketi...",
  "Loading transactions ledger...": "Inapakia miamala...",
  "Loading vouchers…": "Inapakia vocha…",
  "Loading...": "Inapakia...",
  "Loading…": "Inapakia…",
  "Location (optional)": "Mahali (si lazima)",
  "M-Pesa Phone Number": "Namba ya Simu ya M-Pesa",
  "Made": "Zilizotengenezwa",
  "Make vouchers": "Tengeneza vocha",
  "Manage": "Simamia",
  "Manage tenants": "Simamia watoa huduma",
  "Messages": "Ujumbe",
  "Method": "Njia",
  "Method & Ref": "Njia na Kumbukumbu",
  "Minutes": "Dakika",
  "Model": "Modeli",
  "Money waiting": "Pesa inayosubiri",
  "Monthly internet plans for PPPoE subscribers: speed and price.": "Mipango ya intaneti ya kila mwezi kwa wateja wa PPPoE: kasi na bei.",
  "Most popular": "Maarufu zaidi",
  "My Subscription": "Usajili Wangu",
  "Name": "Jina",
  "Name on the portal": "Jina kwenye ukurasa",
  "Name, phone, voucher, IP or MAC": "Jina, simu, vocha, IP au MAC",
  "Needs at least one available Claude model on your account.": "Inahitaji angalau modeli moja ya Claude kwenye akaunti yako.",
  "Network map": "Ramani ya mtandao",
  "New password": "Nenosiri jipya",
  "Next": "Ifuatayo",
  "Next step": "Hatua inayofuata",
  "No ISPs yet": "Bado hakuna watoa huduma",
  "No VLANs yet": "Bado hakuna VLAN",
  "No branches yet": "Bado hakuna matawi",
  "No clients found matching the selected timeframe or search criteria.": "Hakuna wateja wanaolingana na kipindi au utafutaji uliochaguliwa.",
  "No custom domain connected": "Hakuna kikoa maalum kilichounganishwa",
  "No deliveries yet.": "Bado hakuna utumaji.",
  "No limit": "Bila kikomo",
  "No open invoices match.": "Hakuna ankara wazi zinazolingana.",
  "No package sales in this period.": "Hakuna mauzo ya vifurushi katika kipindi hiki.",
  "No packages defined": "Hakuna vifurushi vilivyowekwa",
  "No packages yet": "Bado hakuna vifurushi",
  "No payments in this period": "Hakuna malipo katika kipindi hiki",
  "No payments yet": "Bado hakuna malipo",
  "No revenue records found for this period or search criteria.": "Hakuna rekodi za mapato kwa kipindi au utafutaji huu.",
  "No routers linked yet": "Bado hakuna ruta zilizounganishwa",
  "No routers yet": "Bado hakuna ruta",
  "No sales yet": "Bado hakuna mauzo",
  "No tickets here": "Hakuna tiketi hapa",
  "No tokens yet.": "Bado hakuna tokeni.",
  "No webhook endpoints yet.": "Bado hakuna webhooks.",
  "Nobody at risk right now": "Hakuna aliye hatarini sasa",
  "None on record": "Hakuna kwenye rekodi",
  "None yet": "Bado hakuna",
  "Not a known customer or voucher": "Si mteja wala vocha inayojulikana",
  "Not a secret — this is meant to be visible in the page, same as on any website.": "Si siri: inakusudiwa kuonekana kwenye ukurasa, kama kwenye tovuti yoyote.",
  "Not connected yet": "Bado haijaunganishwa",
  "Nothing matches this filter right now.": "Hakuna kinacholingana na kichujio hiki sasa.",
  "Offline": "Nje ya mtandao",
  "On portal": "Kwenye ukurasa",
  "Once overdue": "Ikishachelewa",
  "Online": "Mtandaoni",
  "Online and paid": "Mtandaoni na wamelipa",
  "Online users": "Watumiaji mtandaoni",
  "Only you so far": "Wewe peke yako kwa sasa",
  "Open": "Wazi",
  "Open Studio": "Fungua Studio",
  "Or link with a phone number": "Au unganisha kwa namba ya simu",
  "Other services": "Huduma nyingine",
  "Overdue": "Imechelewa",
  "Owed": "Deni",
  "PPPoE online": "PPPoE mtandaoni",
  "Package": "Kifurushi",
  "Package Name": "Jina la Kifurushi",
  "Package assistant": "Msaidizi wa vifurushi",
  "Packages": "Vifurushi",
  "Packages customers buy with M-Pesa, cash vouchers, and the Wi-Fi sign-in page they see.": "Vifurushi wateja hununua kwa M-Pesa, vocha za pesa taslimu, na ukurasa wa kuingia Wi-Fi wanaouona.",
  "Paid": "Imelipwa",
  "Paid by": "Imelipwa na",
  "Password": "Nenosiri",
  "Pay with M-Pesa and connect instantly": "Lipa kwa M-Pesa na uunganishwe papo hapo",
  "Paying Clients": "Wateja Wanaolipa",
  "Payment History": "Historia ya Malipo",
  "Payments": "Malipo",
  "Payments that arrived without an invoice to settle. Apply each one to the right invoice so the customer's balance and service are correct.": "Malipo yaliyofika bila ankara ya kulipia. Weka kila moja kwenye ankara sahihi ili salio na huduma ya mteja viwe sawa.",
  "Period": "Kipindi",
  "Period:": "Kipindi:",
  "Person": "Mtu",
  "Phone": "Simu",
  "Phone (MAC)": "Simu (MAC)",
  "Phone (optional)": "Simu (si lazima)",
  "Phones on your hotspot are sent here automatically. You can also share it.": "Simu kwenye hotspot yako huletwa hapa kiotomatiki. Unaweza pia kuushiriki.",
  "Plan": "Mpango",
  "Platform status": "Hali ya jukwaa",
  "Portal add-ons: announcements, social links, ads, live chat and other extras on the sign-in page.": "Nyongeza za ukurasa: matangazo, viungo vya mitandao ya kijamii, gumzo na zaidi kwenye ukurasa wa kuingia.",
  "Portal preview": "Hakikisho la ukurasa",
  "Prepaid voucher": "Vocha ya kulipia kabla",
  "Preparing your QR code…": "Inaandaa msimbo wako wa QR…",
  "Previous": "Iliyotangulia",
  "Price": "Bei",
  "Price (KES)": "Bei (KES)",
  "Price (KES, e.g. 2500.00)": "Bei (KES, mf. 2500.00)",
  "Price (KSh)": "Bei (KSh)",
  "Primary": "Kuu",
  "Print": "Chapisha",
  "Print / PDF Report": "Chapisha / Ripoti ya PDF",
  "Print / Save PDF": "Chapisha / Hifadhi PDF",
  "Printable codes you sell for cash. Each one works once, for the time and limits below.": "Misimbo ya kuchapisha unayouza kwa pesa taslimu. Kila mmoja hufanya kazi mara moja, kwa muda na mipaka iliyo hapa chini.",
  "Priority": "Kipaumbele",
  "Profile": "Wasifu",
  "Provisioning": "Usanidi",
  "Published. Customers see it now.": "Imechapishwa. Wateja wanaiona sasa.",
  "Purchases made on your hotspot portal appear here.": "Manunuzi kwenye hotspot yako yanaonekana hapa.",
  "Querying top consumers...": "Inatafuta watumiaji wakubwa...",
  "RADIUS Data Accounting": "Hesabu ya Data ya RADIUS",
  "Receipt": "Risiti",
  "Receipt #": "Risiti #",
  "Receipts generated": "Risiti zilizotolewa",
  "Received": "Imepokelewa",
  "Received but not yet on an invoice": "Imepokelewa lakini bado haiko kwenye ankara",
  "Recommended": "Inapendekezwa",
  "Reconciliation": "Upatanisho",
  "Reconnecting later needs a new QR scan.": "Kuunganisha tena baadaye kunahitaji kuchanganua QR upya.",
  "Recorded by RADIUS": "Imerekodiwa na RADIUS",
  "Reference": "Kumbukumbu",
  "Refreshes every minute": "Husasishwa kila dakika",
  "Reminders and tickets": "Vikumbusho na tiketi",
  "Remove": "Ondoa",
  "Rename": "Badilisha jina",
  "Renew Now": "Fanya Upya Sasa",
  "Replied": "Imejibiwa",
  "Reports": "Ripoti",
  "Requests from subscribers, hotspot walk-ins, and staff — reply, assign, and track to resolution.": "Maombi kutoka kwa wateja, watumiaji wa hotspot na wafanyakazi: jibu, kabidhi na fuatilia hadi yatatuliwe.",
  "Response": "Jibu",
  "Restore access": "Rejesha huduma",
  "Reveal secret": "Onyesha siri",
  "Revenue & Financials": "Mapato na Fedha",
  "Revenue Breakdown by Payment Channel": "Mapato kwa Njia ya Malipo",
  "Revenue by month": "Mapato kwa mwezi",
  "Revenue per day, last 30 days": "Mapato kwa siku, siku 30 zilizopita",
  "Revenue per month": "Mapato kwa mwezi",
  "Revenue will be charted here as payments come in.": "Mapato yataonyeshwa hapa malipo yanapoingia.",
  "Revenue, customer spending and bandwidth, with receipts and exports.": "Mapato, matumizi ya wateja na data, pamoja na risiti na uhamishaji.",
  "Revoke": "Batilisha",
  "Revoked": "Imebatilishwa",
  "Role": "Jukumu",
  "Roles": "Majukumu",
  "Router": "Ruta",
  "Router map": "Ramani ya ruta",
  "Routers": "Ruta",
  "Sales": "Mauzo",
  "Saved": "Imehifadhiwa",
  "Scan this from the phone you want to connect": "Changanua hii kwa simu unayotaka kuunganisha",
  "Schedule": "Ratiba",
  "Scope": "Wigo",
  "Search client name, phone or #...": "Tafuta jina la mteja, simu au #...",
  "Search receipt, client or M-Pesa ref...": "Tafuta risiti, mteja au kumbukumbu ya M-Pesa...",
  "Search subscriber username...": "Tafuta jina la mtumiaji...",
  "Send a message to test the bot.": "Tuma ujumbe kujaribu bot.",
  "Send by SMS": "Tuma kwa SMS",
  "Send by WhatsApp": "Tuma kwa WhatsApp",
  "Send by email": "Tuma kwa barua pepe",
  "Send test": "Tuma jaribio",
  "Sent the day before the connection is suspended.": "Hutumwa siku moja kabla ya huduma kusimamishwa.",
  "Sent the day the invoice becomes overdue.": "Hutumwa siku ankara inapochelewa.",
  "Service": "Huduma",
  "Service / Description": "Huduma / Maelezo",
  "Sessions": "Vipindi",
  "Sessions appear here as soon as a router reports them over RADIUS accounting.": "Vipindi huonekana hapa mara ruta inapoviripoti kupitia hesabu ya RADIUS.",
  "Set up your account": "Andaa akaunti yako",
  "Settings": "Mipangilio",
  "Share it with them privately. They can change it under Settings → Password.": "Mpe kwa faragha. Anaweza kulibadilisha kwenye Mipangilio → Nenosiri.",
  "Shown to every customer on the Wi-Fi sign-in page.": "Huonyeshwa kwa kila mteja kwenye ukurasa wa kuingia Wi-Fi.",
  "Shown with home internet (fibre) offers.": "Huonyeshwa pamoja na ofa za intaneti ya nyumbani (fibre).",
  "Sign in to an ISP account to edit its portal.": "Ingia kwenye akaunti ya mtoa huduma ili kuhariri ukurasa wake.",
  "Signing secret": "Siri ya kusaini",
  "Since": "Tangu",
  "Site": "Eneo",
  "Source": "Chanzo",
  "Speed": "Kasi",
  "Staff": "Wafanyakazi",
  "Staff and roles": "Wafanyakazi na majukumu",
  "Staff dashboard": "Dashibodi ya wafanyakazi",
  "Start Chat": "Anza Gumzo",
  "Static IP and IPTV": "IP ya kudumu na IPTV",
  "Status": "Hali",
  "Stops one buyer re-sharing this package to other devices. Can also block legitimate travel routers.": "Huzuia mnunuzi mmoja kushiriki kifurushi hiki na vifaa vingine. Inaweza pia kuzuia ruta halali za safari.",
  "Store prices": "Bei za duka",
  "Subheading": "Kichwa kidogo",
  "Subject": "Mada",
  "Subnet": "Subnet",
  "Subscriber Username": "Jina la Mtumiaji",
  "Subscribers in view": "Wateja wanaoonekana",
  "Subscribers who used the most data, PPPoE and hotspot.": "Wateja waliotumia data nyingi zaidi, PPPoE na hotspot.",
  "Subscriptions off for non-payment": "Huduma zilizozimwa kwa kutolipa",
  "Support number": "Namba ya msaada",
  "Support response targets": "Malengo ya muda wa kujibu",
  "Support tickets": "Tiketi za msaada",
  "Suspend": "Simamisha",
  "Suspended": "Imesimamishwa",
  "Suspended, overdue, or a paying customer who has gone quiet. Call them before they leave.": "Waliosimamishwa, waliochelewa, au mteja aliyekuwa analipa na amenyamaza. Wapigie kabla hawajaondoka.",
  "Tagged network segments and their provisioning status": "Sehemu za mtandao zilizowekwa lebo na hali ya usanidi wake",
  "Target": "Lengo",
  "Tawk.to widget ID": "Kitambulisho cha Tawk.to",
  "Temporary password": "Nenosiri la muda",
  "Test Bot": "Jaribu Bot",
  "The latest 100.": "100 za karibuni.",
  "The ten most recent tenants": "Watoa huduma kumi wa karibuni",
  "The towns or areas you run. Put routers, customers and staff in a branch to filter lists and analytics by it.": "Miji au maeneo unayohudumia. Weka ruta, wateja na wafanyakazi kwenye tawi ili kuchuja orodha na takwimu kwa tawi hilo.",
  "This Month": "Mwezi Huu",
  "This Week": "Wiki Hii",
  "This month": "Mwezi huu",
  "This takes a few seconds.": "Hii huchukua sekunde chache.",
  "Three messages go out at most: before the due date, once overdue, and the day before suspension. Each is sent once per invoice.": "Ujumbe usiozidi mitatu hutumwa: kabla ya tarehe ya mwisho, ikishachelewa, na siku moja kabla ya kusimamishwa. Kila mmoja hutumwa mara moja kwa kila ankara.",
  "Today (Day)": "Leo (Siku)",
  "Total Client Spend": "Jumla ya Matumizi ya Wateja",
  "Total Clients": "Jumla ya Wateja",
  "Total Data": "Jumla ya Data",
  "Total Revenue": "Jumla ya Mapato",
  "Total Spends (KES)": "Jumla ya Matumizi (KES)",
  "Total data": "Jumla ya data",
  "Track when subscribers joined, their lifetime spending, and view receipts.": "Fuatilia wateja walijiunga lini, matumizi yao yote, na uone risiti.",
  "Transactions": "Miamala",
  "Transactions & Stamped Receipts": "Miamala na Risiti Zilizogongwa Muhuri",
  "Type": "Aina",
  "Type a message...": "Andika ujumbe...",
  "Unique subscribers & guests": "Wateja na wageni tofauti",
  "Unknown payer": "Mlipaji asiyejulikana",
  "Unlimited": "Bila kikomo",
  "Unlocks": "Hufungua",
  "Unmatched payments": "Malipo yasiyolinganishwa",
  "Update speed tiers and monthly pricing.": "Sasisha viwango vya kasi na bei za kila mwezi.",
  "Updated": "Imesasishwa",
  "Upload (Mbps)": "Kupakia (Mbps)",
  "Upload (Tx)": "Kupakia (Tx)",
  "Upload Speed (Kbps)": "Kasi ya Kupakia (Kbps)",
  "Upload speed (Mbps)": "Kasi ya kupakia (Mbps)",
  "Uploaded": "Iliyopakiwa",
  "Used": "Imetumika",
  "VLANs": "VLAN",
  "View all": "Tazama zote",
  "Voucher": "Vocha",
  "Voucher and account logins": "Kuingia kwa vocha na akaunti",
  "Webhooks": "Webhooks",
  "What customers can buy on your hotspot portal.": "Wateja wanachoweza kununua kwenye hotspot yako.",
  "What customers can buy on your hotspot. Switched-off packages stay here but don't show on the portal.": "Wateja wanachoweza kununua kwenye hotspot yako. Vifurushi vilivyozimwa hubaki hapa lakini havionekani kwenye ukurasa.",
  "What each role can do": "Kila jukumu linaweza kufanya nini",
  "What it can do": "Kinachoweza kufanya",
  "What it unlocks": "Kinachofungua",
  "What sells": "Kinachouzika",
  "What this number now does": "Namba hii sasa inafanya nini",
  "WhatsApp": "WhatsApp",
  "WhatsApp messages use the SMS wording and go out from the number linked under Settings → WhatsApp. Without a linked number they are skipped.": "Ujumbe wa WhatsApp hutumia maneno ya SMS na hutoka kwenye namba iliyounganishwa kwenye Mipangilio → WhatsApp. Bila namba iliyounganishwa hurukwa.",
  "When customers are reminded to pay, what the messages say, and how fast support must answer.": "Wateja hukumbushwa kulipa lini, ujumbe unasema nini, na msaada lazima ujibu kwa haraka gani.",
  "When customers pay": "Wateja hulipa lini",
  "Where it shows": "Mahali kinaonekana",
  "Where your routers are and which ones are reporting. Click a router in the list, then click the map to place it.": "Ruta zako ziko wapi na zipi zinaripoti. Bofya ruta kwenye orodha, kisha bofya ramani kuiweka.",
  "Who": "Nani",
  "Who can sign in to this dashboard, and what each person may do.": "Nani anaweza kuingia kwenye dashibodi hii, na kila mtu anaruhusiwa kufanya nini.",
  "Why": "Sababu",
  "Widget ID": "Kitambulisho cha kisanduku",
  "Write a reply...": "Andika jibu...",
  "Your Platform Domain": "Kikoa Chako cha Jukwaa",
  "Your business name": "Jina la biashara yako",
  "Your current plan, usage, and renewal history.": "Mpango wako wa sasa, matumizi, na historia ya kufanya upya.",
  "Your customers are being messaged from a shared number": "Wateja wako wanatumiwa ujumbe kutoka namba ya pamoja",
  "Your platform subdomain always works — connect a custom domain if you want your own branded URL.": "Kikoa kidogo chako cha jukwaa hufanya kazi daima. Unganisha kikoa maalum ukitaka URL yenye chapa yako.",
  "Your portal link": "Kiungo cha ukurasa wako",
  "Your profile and sign-in security.": "Wasifu wako na usalama wa kuingia.",
  "anything a customer replies there is discarded": "jibu lolote la mteja pale hutupwa",
  "e.g. 1 hour": "mf. saa 1",
  "e.g. Fiber Premium 20Mbps": "mf. Fiber Premium 20Mbps",
  "e.g. KSh 1,500": "mf. KSh 1,500",
  "e.g. Kasarani": "mf. Kasarani",
  "e.g. Nairobi, Thika Road": "mf. Nairobi, Thika Road",
  "e.g. Sync payments to our accounting system": "mf. Sawazisha malipo na mfumo wetu wa hesabu",
  "e.g. claude-desktop — so you know which one to revoke": "mf. claude-desktop, ili ujue upi wa kubatilisha",
  "to": "hadi",
  "you": "wewe",
  "• Answers customers with a self-service menu (balance, buy Wi-Fi, report an outage, support)": "• Hujibu wateja kwa menyu ya kujihudumia (salio, nunua Wi-Fi, ripoti hitilafu, msaada)",

  "Suspended for non-payment": "Imesimamishwa kwa kutolipa",
  "Invoice overdue": "Ankara imechelewa",
  "No payment in over 40 days": "Hakuna malipo kwa zaidi ya siku 40",
  "Sunday": "Jumapili",
  "Monday": "Jumatatu",
  "Tuesday": "Jumanne",
  "Wednesday": "Jumatano",
  "Thursday": "Alhamisi",
  "Friday": "Ijumaa",
  "Saturday": "Jumamosi",
  "Send alert": "Tuma arifa",
  "% of their data cap in 30 days": "% ya kikomo chao cha data kwa siku 30",
  "1 day before": "Siku 1 kabla",
  "12 hours before": "Saa 12 kabla",
  "2 days before": "Siku 2 kabla",
  "2 hours before": "Saa 2 kabla",
  "A referrer with no active plan to extend gets the account credit instead.": "Aliyeleta mteja asiye na mpango hai wa kuongezewa hupata salio la akaunti badala yake.",
  "Account credit (KES):": "Salio la akaunti (KES):",
  "Add": "Ongeza",
  "Address or landmark": "Anwani au alama ya karibu",
  "All customers": "Wateja wote",
  "All jobs": "Kazi zote",
  "An installation needs the customer's signature before it can be closed.": "Ufungaji unahitaji sahihi ya mteja kabla ya kufungwa.",
  "Applied": "Imetekelezwa",
  "Before VAT": "Kabla ya VAT",
  "Call": "Piga simu",
  "Cancel job": "Ghairi kazi",
  "Cancel this job?": "Ghairi kazi hii?",
  "Cancel this maintenance? Customers already told will get a text saying it is off.": "Ghairi matengenezo haya? Wateja walioambiwa watapokea ujumbe kwamba yameahirishwa.",
  "Cancelled": "Imeghairiwa",
  "Cancelled.": "Imeghairiwa.",
  "Cancelled. Customers told:": "Imeghairiwa. Wateja walioarifiwa:",
  "Choose a branch.": "Chagua tawi.",
  "Choose a branch…": "Chagua tawi…",
  "Choose at least one router.": "Chagua angalau ruta moja.",
  "Clear": "Futa",
  "Close job": "Funga kazi",
  "Close the job": "Funga kazi",
  "Closed": "Imefungwa",
  "Contact phone": "Simu ya mawasiliano",
  "Create a job and assign it to a technician. They get an alert on their phone.": "Unda kazi na umpe fundi. Atapata arifa kwenye simu yake.",
  "Create job": "Unda kazi",
  "Customer (optional)": "Mteja (si lazima)",
  "Customer signature": "Sahihi ya mteja",
  "Customers on a router are those whose plan runs on it or who connected through it in the last 30 days.": "Wateja wa ruta ni wale ambao mpango wao uko juu yake au waliounganishwa kupitia hiyo siku 30 zilizopita.",
  "Customers told": "Wateja wameambiwa",
  "Customers who will be texted:": "Wateja watakaotumiwa ujumbe:",
  "Date": "Tarehe",
  "Dismissed": "Imekataliwa",
  "Dismissed.": "Imekataliwa.",
  "Done": "Imekamilika",
  "Ends": "Inaisha",
  "Equipment fitted": "Vifaa vilivyofungwa",
  "Every customer has a referral code. Enter it when you add a new customer; once the new customer pays for the first time, the one who referred them is rewarded.": "Kila mteja ana msimbo wa rufaa. Uweke unapoongeza mteja mpya; mteja mpya akilipa mara ya kwanza, aliyemleta anazawadiwa.",
  "Everyone": "Kila mtu",
  "Extra line for customers (optional)": "Ujumbe wa ziada kwa wateja (si lazima)",
  "Field work": "Kazi za uwanjani",
  "Finished": "Imemalizika",
  "For your team. Customers see the time and the extra line below.": "Kwa timu yako. Wateja huona muda na ujumbe wa ziada ulio hapa chini.",
  "Free days on their plan:": "Siku za bure kwenye mpango wao:",
  "Has referred": "Amewaleta",
  "Hotspot and voucher sales": "Mauzo ya hotspot na vocha",
  "I have arrived, start the job": "Nimefika, anza kazi",
  "In progress": "Inaendelea",
  "Installation": "Ufungaji",
  "Installations, repairs and site visits. Open a job on your phone to start it, add photos and close it with the customer's signature.": "Ufungaji, marekebisho na ziara za eneo. Fungua kazi kwenye simu yako ili kuianza, ongeza picha na uifunge kwa sahihi ya mteja.",
  "Invoice": "Ankara",
  "Invoiced subscriptions": "Usajili uliotolewa ankara",
  "Invoices": "Ankara",
  "Job photo": "Picha ya kazi",
  "Jobs assigned to you appear here.": "Kazi ulizopewa zinaonekana hapa.",
  "KRA PIN": "PIN ya KRA",
  "KRA PIN not set": "PIN ya KRA haijawekwa",
  "Look for subscribers who need a bigger plan": "Tafuta wateja wanaohitaji mpango mkubwa zaidi",
  "Maintenance": "Matengenezo",
  "Maintenance you schedule appears here.": "Matengenezo unayopanga yanaonekana hapa.",
  "Mine": "Zangu",
  "Month": "Mwezi",
  "Name of the person signing": "Jina la anayesaini",
  "New customer": "Mteja mpya",
  "New job": "Kazi mpya",
  "No customer yet": "Bado hakuna mteja",
  "No finished jobs": "Hakuna kazi zilizokamilika",
  "No invoice; prices include VAT at your standard rate.": "Hakuna ankara; bei zinajumuisha VAT kwa kiwango chako cha kawaida.",
  "No invoices this month": "Hakuna ankara mwezi huu",
  "No invoices this month.": "Hakuna ankara mwezi huu.",
  "No open jobs": "Hakuna kazi zilizo wazi",
  "No photos.": "Hakuna picha.",
  "No rewards yet": "Bado hakuna zawadi",
  "No time set": "Muda haujawekwa",
  "Nobody needs a bigger plan right now": "Hakuna anayehitaji mpango mkubwa sasa",
  "Not assigned": "Hajapewa mtu",
  "Notes for the technician": "Maelezo kwa fundi",
  "Nothing planned": "Hakuna kilichopangwa",
  "Nothing to do": "Hakuna la kufanya",
  "Now": "Sasa",
  "On site": "Yuko eneo la kazi",
  "Open in Maps": "Fungua kwenye Ramani",
  "Output VAT": "VAT ya mauzo",
  "Photos": "Picha",
  "Photos are shrunk on the phone before upload, so they send quickly on mobile data.": "Picha hupunguzwa ukubwa kwenye simu kabla ya kutumwa, hivyo hutumwa haraka kwa data ya simu.",
  "Plan upgrades": "Kuongeza vifurushi",
  "Planned maintenance": "Matengenezo yaliyopangwa",
  "Refer a neighbour": "Mlete jirani",
  "Referral code": "Msimbo wa rufaa",
  "Referral code (optional)": "Msimbo wa rufaa (si lazima)",
  "Referrals": "Rufaa",
  "Referred by": "Aliletwa na",
  "Relocation": "Kuhamisha",
  "Removal": "Kuondoa",
  "Removed router": "Ruta iliyoondolewa",
  "Repair": "Marekebisho",
  "Reward": "Zawadi",
  "Reward customers who refer a neighbour": "Zawadia wateja wanaoleta jirani",
  "Rewarded": "Amezawadiwa",
  "Rewards appear here when a referred customer makes their first payment.": "Zawadi huonekana hapa mteja aliyeletwa anapolipa mara ya kwanza.",
  "Rewards given": "Zawadi zilizotolewa",
  "Sales and VAT for one month, in your timezone, for the KRA VAT return.": "Mauzo na VAT kwa mwezi mmoja, kwa saa za eneo lako, kwa ajili ya ritani ya VAT ya KRA.",
  "Sales before VAT": "Mauzo kabla ya VAT",
  "Sales including VAT": "Mauzo pamoja na VAT",
  "Save": "Hifadhi",
  "Saving…": "Inahifadhi…",
  "Schedule and notify": "Panga na uarifu",
  "Schedule maintenance": "Panga matengenezo",
  "Scheduled": "Imepangwa",
  "Scheduled and past": "Yaliyopangwa na yaliyopita",
  "Scheduled. Customers are texted before it starts and again when it is over.": "Imepangwa. Wateja watatumiwa ujumbe kabla ya kuanza na tena yakiisha.",
  "Search customers": "Tafuta wateja",
  "Search name or phone": "Tafuta jina au simu",
  "Signed by": "Imesainiwa na",
  "Site survey": "Ukaguzi wa eneo",
  "Something went wrong.": "Kuna tatizo limetokea.",
  "Standard VAT rate (%)": "Kiwango cha kawaida cha VAT (%)",
  "Starting…": "Inaanza…",
  "Starts": "Inaanza",
  "Subscribers who used most of their data cap in the last 30 days, and the next plan up. Apply moves them onto it now.": "Wateja waliotumia sehemu kubwa ya kikomo chao cha data siku 30 zilizopita, na mpango unaofuata. Tekeleza huwahamishia sasa hivi.",
  "Suggest when they have used": "Pendekeza wanapokuwa wametumia",
  "Suggested": "Unapendekezwa",
  "Suggestions": "Mapendekezo",
  "Take or add photos": "Piga au ongeza picha",
  "Technician": "Fundi",
  "Tell customers before you work on the network. They get an SMS before it starts and another when it is over.": "Waambie wateja kabla ya kufanya kazi kwenye mtandao. Hupata SMS kabla ya kuanza na nyingine yakiisha.",
  "Text customers": "Tuma ujumbe kwa wateja",
  "Text the customer about the bigger plan": "Mtumie mteja ujumbe kuhusu mpango mkubwa",
  "Texted": "Wametumiwa ujumbe",
  "The system checks every 6 hours for subscribers near their data cap.": "Mfumo hukagua kila saa 6 kwa wateja walio karibu na kikomo chao cha data.",
  "Their code": "Msimbo wake",
  "They get a push alert if they turned alerts on.": "Hupata arifa kama wamewasha arifa.",
  "They get a reward when someone they referred makes a first payment.": "Hupata zawadi mtu waliyemleta anapolipa mara ya kwanza.",
  "To do": "Za kufanya",
  "To review": "Za kukagua",
  "Total": "Jumla",
  "Uploading…": "Inapakia…",
  "Used in 30 days": "Iliyotumika siku 30",
  "VAT": "VAT",
  "VAT details": "Maelezo ya VAT",
  "VAT inside": "VAT iliyomo",
  "VAT report": "Ripoti ya VAT",
  "Waiting for first payment": "Anasubiri malipo ya kwanza",
  "We are registered for VAT": "Tumesajiliwa kwa VAT",
  "What is happening": "Kinachofanyika",
  "What needs doing": "Kinachohitaji kufanywa",
  "What was done": "Kilichofanyika",
  "When": "Lini",
  "Where and who": "Wapi na nani",
  "Who is affected": "Nani ataathirika",
  "Whose": "Za nani",
  "You are not marked as VAT-registered, so hotspot sales show no VAT. Set your VAT details below if you are registered.": "Hujawekwa kama umesajiliwa kwa VAT, hivyo mauzo ya hotspot hayaonyeshi VAT. Weka maelezo yako ya VAT hapa chini kama umesajiliwa.",
  "e.g. Install fibre and ONT": "mf. Funga fibre na ONT",
  "e.g. Kasarani, next to Seasons Mall": "mf. Kasarani, karibu na Seasons Mall",
  "e.g. ONT HWTC89A120FC, 30 m drop cable": "mf. ONT HWTC89A120FC, kebo ya mita 30",
  "e.g. Replacing the Kasarani tower radio": "mf. Kubadilisha redio ya mnara wa Kasarani",
  "e.g. We are upgrading to faster fibre.": "mf. Tunaboresha hadi fibre yenye kasi zaidi.",
  "earned": "amepata",
  "free days": "siku za bure",
  "invoices": "ankara",
  "invoices issued this month": "ankara zilizotolewa mwezi huu",
  "invoices this month carry no VAT. Set a tax rate on your internet plans so new invoices include it.": "ankara za mwezi huu hazina VAT. Weka kiwango cha kodi kwenye mipango yako ya intaneti ili ankara mpya ziijumuishe.",
  "moved to": "amehamishiwa",
  "sales": "mauzo",
  "Anti-tunnel shield off": "Kinga ya kuzuia tunnel imezimwa",
  "Anti-tunnel shield on": "Kinga ya kuzuia tunnel imewashwa",
  "Blocks VPN and tunnel tricks used to get free internet on the hotspot.": "Huzuia mbinu za VPN na tunnel zinazotumiwa kupata intaneti bure kwenye hotspot.",
  "Brings the bootloader up to the installed RouterOS and reboots. Run it after a RouterOS upgrade.": "Husasisha bootloader ilingane na RouterOS iliyosakinishwa na kuwasha upya. Iendeshe baada ya kusasisha RouterOS.",
  "Check versions": "Kagua matoleo",
  "Clear selection": "Ondoa uteuzi",
  "Customers drop for a minute or two": "Wateja hukatika kwa dakika moja au mbili",
  "Downloads the latest RouterOS for the router's update channel and installs it. The router reboots.": "Hupakua RouterOS mpya ya chaneli ya ruta na kuisakinisha. Ruta huwaka upya.",
  "Failed": "Imeshindwa",
  "Fair bandwidth sharing (PCQ)": "Mgawanyo sawa wa kasi (PCQ)",
  "Family-safe DNS off": "DNS salama kwa familia imezimwa",
  "Family-safe DNS on": "DNS salama kwa familia imewashwa",
  "Features": "Vipengele",
  "Firmware": "Firmware",
  "Goes back to standard fast DNS (1.1.1.1, 8.8.8.8).": "Hurudi kwenye DNS ya kawaida yenye kasi (1.1.1.1, 8.8.8.8).",
  "Lets speed test sites run at the line's full speed so customers see what they pay for.": "Huruhusu tovuti za kupima kasi kutumia kasi kamili ili wateja waone wanacholipia.",
  "No updates yet": "Bado hakuna masasisho",
  "Not linked": "Haijaunganishwa",
  "Pick a time": "Chagua muda",
  "Push an update": "Tuma sasisho",
  "Push latest hotspot setup": "Tuma usanidi mpya wa hotspot",
  "Re-applies the current login page, RADIUS server, walled garden and app filter, so routers pick up the platform's newest setup.": "Huweka upya ukurasa wa kuingia, seva ya RADIUS, walled garden na kichujio cha programu, ili ruta zipate usanidi mpya wa jukwaa.",
  "Reads each router's RouterOS version, model and firmware, and whether a RouterOS update is out. Changes nothing.": "Husoma toleo la RouterOS, modeli na firmware ya kila ruta, na kama kuna sasisho la RouterOS. Haibadilishi chochote.",
  "Reboot": "Washa upya",
  "Recent updates": "Masasisho ya karibuni",
  "Removes the anti-tunnel firewall rules.": "Huondoa sheria za firewall za kuzuia tunnel.",
  "Restarts the router. Customers are offline for about a minute.": "Huwasha ruta upya. Wateja hukosa mtandao kwa takriban dakika moja.",
  "Router updates": "Masasisho ya ruta",
  "RouterOS script": "Hati ya RouterOS",
  "Run my RouterOS script": "Endesha hati yangu ya RouterOS",
  "Running": "Inaendelea",
  "Runs exactly as written on every chosen router. Test it on one router first. What the script prints with :put is shown in the results.": "Huendeshwa kama ilivyoandikwa kwenye kila ruta iliyochaguliwa. Ijaribu kwenye ruta moja kwanza. Kinachochapishwa na :put huonyeshwa kwenye matokeo.",
  "Runs your own RouterOS script on each router, exactly as written, and records what it printed.": "Huendesha hati yako ya RouterOS kwenye kila ruta kama ilivyoandikwa, na kurekodi ilichochapisha.",
  "Scheduled. It starts on its own at the time you chose.": "Imepangwa. Itaanza yenyewe kwa muda uliochagua.",
  "Select all online": "Chagua zote zilizo mtandaoni",
  "Shares bandwidth evenly between users so one heavy downloader cannot slow everyone else.": "Hugawa kasi sawa kati ya watumiaji ili mpakuaji mmoja mkubwa asiwapunguzie wengine kasi.",
  "Skipped": "Imerukwa",
  "Slow": "Polepole",
  "Speed test boost": "Kuongeza kasi ya kipimo",
  "Start on": "Anza kwenye",
  "Started. Results appear below as each router is done.": "Imeanza. Matokeo yanaonekana hapa chini kila ruta inapokamilika.",
  "Stop": "Simamisha",
  "Test on the first router, then do the rest": "Jaribu kwenye ruta ya kwanza, kisha zilizobaki",
  "This drops customers on these routers for a minute or two. Continue now?": "Hii itakatisha wateja kwenye ruta hizi kwa dakika moja au mbili. Endelea sasa?",
  "Tick the routers to update above.": "Weka alama kwenye ruta za kusasisha hapo juu.",
  "Tonight at 3:00": "Usiku wa leo saa 9:00",
  "Unknown": "Haijulikani",
  "Update your MikroTik routers over the air: RouterOS and firmware upgrades, the latest hotspot setup, network features, reboots or your own script, on one router or all of them.": "Sasisha ruta zako za MikroTik ukiwa mbali: RouterOS na firmware, usanidi mpya wa hotspot, vipengele vya mtandao, kuwasha upya au hati yako, kwenye ruta moja au zote.",
  "Updates": "Masasisho",
  "Updates you push appear here with a result for each router.": "Masasisho unayotuma yanaonekana hapa pamoja na matokeo ya kila ruta.",
  "Updating": "Inasasisha",
  "Upgrade RouterBOARD firmware": "Sasisha firmware ya RouterBOARD",
  "Upgrade RouterOS": "Sasisha RouterOS",
  "Uses Cloudflare Family DNS, which blocks malware and adult sites.": "Hutumia Cloudflare Family DNS, inayozuia programu hasidi na tovuti za watu wazima.",
  "Versions come from the last “Check versions”. Offline and unlinked routers are skipped.": "Matoleo yanatoka kwenye “Kagua matoleo” ya mwisho. Ruta zisizo mtandaoni au zisizounganishwa hurukwa.",
  "Waiting": "Inasubiri",
  "Your routers": "Ruta zako",
  "done": "zimekamilika",
  "failed": "zimeshindwa",
  "first": "ya kwanza",
  "router": "ruta",
  "routers": "ruta",
  "routers selected": "ruta zimechaguliwa",
  "Plan paused until": "Mpango umesimamishwa hadi",
  "Plan resumed.": "Mpango umeendelea.",
  "Pause this plan for how many days?": "Simamisha mpango huu kwa siku ngapi?",
  "Enter a whole number of days between 1 and 365.": "Weka idadi kamili ya siku kati ya 1 na 365.",
  "Paused until": "Umesimamishwa hadi",
  "PAUSED": "UMESIMAMISHWA",
  "Pause": "Simamisha",
  "Resume": "Endelea",
  "Invite sent by SMS.": "Mwaliko umetumwa kwa SMS.",
  "Share the invite link with them.": "Watumie kiungo cha mwaliko.",
  "added.": "ameongezwa.",
  "New invite ready.": "Mwaliko mpya uko tayari.",
  "Member removed. Their login no longer works.": "Mwanachama ameondolewa. Kuingia kwake hakufanyi kazi tena.",
  "Invite link copied.": "Kiungo cha mwaliko kimenakiliwa.",
  "Copy this invite link:": "Nakili kiungo hiki cha mwaliko:",
  "People on this account": "Watu kwenye akaunti hii",
  "Family or colleagues who can sign in to see the plans, bills and usage, and ask for help. Only people you allow can pay.": "Familia au wafanyakazi wenzako wanaoweza kuingia kuona mipango, bili na matumizi, na kuomba msaada. Ni wale tu unaowaruhusu wanaoweza kulipa.",
  "Add person": "Ongeza mtu",
  "Phone (optional, for the invite SMS)": "Simu (si lazima, kwa SMS ya mwaliko)",
  "Allowed to pay bills": "Anaruhusiwa kulipa bili",
  "Adding…": "Inaongeza…",
  "Add and invite": "Ongeza na ualike",
  "Only the account holder so far": "Mwenye akaunti pekee kwa sasa",
  "Signed up": "Amejisajili",
  "Invited": "Amealikwa",
  "Invite expired": "Mwaliko umeisha muda",
  "Can pay": "Anaweza kulipa",
  "View only": "Kuona tu",
  "Copy invite link": "Nakili kiungo cha mwaliko",
  "New invite": "Mwaliko mpya",
  "Make view only": "Fanya kuona tu",
  "Allow paying": "Ruhusu kulipa",
  "Their login stops working.": "Kuingia kwake kutaacha kufanya kazi.",
  "10 GB top-up": "Nyongeza ya GB 10",
  "Add-on": "Nyongeza",
  "Add-ons": "Nyongeza",
  "Boost my internet": "Ongeza kasi ya intaneti yangu",
  "Check your phone and enter your M-Pesa PIN…": "Angalia simu yako na uweke PIN yako ya M-Pesa…",
  "Create a speed boost or data top-up above. Customers see active ones in their app.": "Unda nyongeza ya kasi au data hapo juu. Wateja wanaziona zilizo hai kwenye programu yao.",
  "Create an add-on first, under Add-ons.": "Unda nyongeza kwanza, chini ya Nyongeza.",
  "Download, Mbps": "Kupakua, Mbps",
  "Enter one of the numbers shown.": "Weka mojawapo ya nambari zilizoonyeshwa.",
  "Extra data": "Data ya ziada",
  "Extra data raises the plan's data cap while it runs, so the customer is not asked to upgrade.": "Data ya ziada huongeza kikomo cha data cha mpango inapoendelea, hivyo mteja haombwi kupandisha mpango.",
  "Extra data, GB": "Data ya ziada, GB",
  "Faster speed or extra data for a while, paid with M-Pesa. It starts as soon as you pay.": "Kasi zaidi au data ya ziada kwa muda, kulipwa kwa M-Pesa. Inaanza mara tu unapolipa.",
  "Free": "Bure",
  "Give add-on": "Toa nyongeza",
  "Give which add-on for free? Enter its number:": "Toa nyongeza ipi bure? Weka nambari yake:",
  "Hidden": "Imefichwa",
  "Hide": "Ficha",
  "Install card": "Kadi ya usakinishaji",
  "Lasts, hours": "Inadumu, saa",
  "M-Pesa phone": "Simu ya M-Pesa",
  "New add-on": "Nyongeza mpya",
  "No add-ons yet": "Hakuna nyongeza bado",
  "Nothing bought yet": "Hakuna kilichonunuliwa bado",
  "On offer": "Zinazouzwa",
  "On sale": "Inauzwa",
  "Only the account holder can buy add-ons.": "Mwenye akaunti pekee ndiye anayeweza kununua nyongeza.",
  "Paid. Your add-on is on. If you were online, your connection restarts for a few seconds.": "Umelipa. Nyongeza yako imewashwa. Kama ulikuwa mtandaoni, muunganisho wako utaanza upya kwa sekunde chache.",
  "Payment failed.": "Malipo hayakufaulu.",
  "Put on sale": "Weka iuzwe",
  "Recent purchases": "Manunuzi ya karibuni",
  "Send M-Pesa prompt": "Tuma ombi la M-Pesa",
  "Sending…": "Inatuma…",
  "Speed boost": "Nyongeza ya kasi",
  "Speed boosts and extra data your PPPoE customers buy in their app with M-Pesa. Each one starts as soon as it is paid and ends by itself.": "Nyongeza za kasi na data ya ziada ambazo wateja wako wa PPPoE hununua kwenye programu yao kwa M-Pesa. Kila moja huanza mara inapolipwa na kuisha yenyewe.",
  "The prompt was cancelled.": "Ombi lilighairiwa.",
  "Try again": "Jaribu tena",
  "Upload, Mbps": "Kupakia, Mbps",
  "Weekend boost 20 Mbps": "Nyongeza ya wikendi Mbps 20",
  "What they get": "Wanachopata",
  "day": "siku",
  "days": "siku",
  "hours": "saa",
  "is on until": "imewashwa hadi",
  "paid": "zimelipwa",
  "Offer sent to": "Ofa imetumwa kwa",
  "The SMS could not be sent. Check the SMS gateway under Settings.": "SMS haikuweza kutumwa. Angalia lango la SMS kwenye Mipangilio.",
  "Win-back offers": "Ofa za kuwarudisha wateja",
  "Customers who are suspended, overdue or have stopped paying get a text: pay within a few days and get part of it back as credit. See who came back.": "Wateja waliosimamishwa, waliochelewa au walioacha kulipa wanapata ujumbe: lipa ndani ya siku chache upate sehemu yake kama salio. Ona nani amerudi.",
  "Offers sent": "Ofa zilizotumwa",
  "waiting": "zinasubiri",
  "Came back": "Wamerudi",
  "of finished offers": "ya ofa zilizokamilika",
  "No finished offers yet": "Hakuna ofa zilizokamilika bado",
  "Recovered": "Zilizorejeshwa",
  "Paid inside the offer window": "Zimelipwa ndani ya muda wa ofa",
  "Credit given": "Salio lililotolewa",
  "The cost of the offers that worked": "Gharama ya ofa zilizofaulu",
  "Could get an offer": "Wanaweza kupata ofa",
  "At risk now and no offer in the waiting period. The automatic job texts these in the daytime when offers are on.": "Wako hatarini sasa na hawajapata ofa katika kipindi cha kusubiri. Kazi ya kiotomatiki huwatumia ujumbe mchana ofa zikiwa zimewashwa.",
  "Owes": "Anadaiwa",
  "Text an offer to": "Tuma ofa kwa",
  "Send offer": "Tuma ofa",
  "Offers": "Ofa",
  "No offers sent yet": "Hakuna ofa zilizotumwa bado",
  "Sent": "Imetumwa",
  "Result": "Matokeo",
  "Credit": "Salio",
  "By staff": "Na mfanyakazi",
  "Automatic": "Kiotomatiki",
  "until": "hadi",
  "Expired": "Imeisha muda",
  "SMS failed": "SMS haikufika",
  "Offer": "Ofa",
  "Each offer is one SMS, sent between 9am and 6pm.": "Kila ofa ni SMS moja, hutumwa kati ya saa 3 asubuhi na saa 12 jioni.",
  "Send offers automatically": "Tuma ofa kiotomatiki",
  "Credit back, %": "Salio la kurudishwa, %",
  "Offer lasts, days": "Ofa inadumu, siku",
  "Days before the same customer can get another": "Siku kabla mteja huyo kupata nyingine",
  "Example: with 20%, a customer who owes KES 1,500 and pays it in time gets KES 300 credit on their next bill.": "Mfano: kwa 20%, mteja anayedaiwa KES 1,500 akilipa kwa wakati anapata salio la KES 300 kwenye bili ijayo.",
  "Sent by staff": "Imetumwa na mfanyakazi",
  "Last 90 days": "Siku 90 zilizopita",
  "Add a shop to start selling vouchers through it.": "Ongeza duka ili kuanza kuuza vocha kupitia kwake.",
  "Add agent": "Ongeza wakala",
  "Agent": "Wakala",
  "Agent added. Send them this invite link to set up their login:": "Wakala ameongezwa. Mtumie kiungo hiki cha mwaliko ili aweke kuingia kwake:",
  "Agent added. Their invite was sent by SMS.": "Wakala ameongezwa. Mwaliko wake umetumwa kwa SMS.",
  "Agents": "Mawakala",
  "Agents owe you": "Mawakala wanakudai",
  "All agents": "Mawakala wote",
  "Bank": "Benki",
  "Bill payment commission, %": "Kamisheni ya malipo ya bili, %",
  "Bill payments": "Malipo ya bili",
  "Cash": "Taslimu",
  "Choose…": "Chagua…",
  "Commission": "Kamisheni",
  "Commission this month": "Kamisheni mwezi huu",
  "Give vouchers": "Toa vocha",
  "How": "Njia",
  "Location": "Mahali",
  "Money handed over": "Pesa zilizokabidhiwa",
  "New agent": "Wakala mpya",
  "New invite link:": "Kiungo kipya cha mwaliko:",
  "New invite sent by SMS.": "Mwaliko mpya umetumwa kwa SMS.",
  "No agents yet": "Hakuna mawakala bado",
  "No vouchers in stock.": "Hakuna vocha zilizopo.",
  "Owes you": "Anakudai",
  "Record hand-over": "Rekodi makabidhiano",
  "Recorded. They now owe": "Imerekodiwa. Sasa anadaiwa",
  "Reference (optional)": "Kumbukumbu (si lazima)",
  "Resend invite": "Tuma mwaliko tena",
  "Shop or agent name": "Jina la duka au wakala",
  "Shops that sell your WiFi vouchers and take customers' bill payments in cash, for a commission. Each agent has their own app at /agent.": "Maduka yanayouza vocha zako za WiFi na kupokea malipo ya bili za wateja kwa taslimu, kwa kamisheni. Kila wakala ana programu yake kwenye /agent.",
  "Statement": "Taarifa",
  "Suspend this agent? They can't sell or take payments until you turn them back on.": "Simamisha wakala huyu? Hataweza kuuza wala kupokea malipo hadi umrudishe.",
  "Suspended: this agent can't sell or take payments.": "Amesimamishwa: wakala huyu hawezi kuuza wala kupokea malipo.",
  "Taken this month": "Zilizopokelewa mwezi huu",
  "They owe": "Anadaiwa",
  "Turn back on": "Rudisha",
  "Voucher commission, %": "Kamisheni ya vocha, %",
  "Voucher stock": "Vocha zilizopo",
  "Vouchers": "Vocha",
  "Vouchers in stock": "Vocha zilizopo",
  "Vouchers with agents": "Vocha kwa mawakala",
  "You can't record payments.": "Huwezi kurekodi malipo.",
  "vouchers added to their stock.": "vocha zimeongezwa kwenye akiba yake.",
  "Active customers": "Wateja walio hai",
  "Add:": "Ongeza:",
  "All campaigns": "Kampeni zote",
  "All plans": "Mipango yote",
  "Both": "Zote mbili",
  "Brought in": "Zilizoletwa",
  "Campaign": "Kampeni",
  "Campaigns": "Kampeni",
  "Count payments for, days": "Hesabu malipo kwa siku",
  "Haven't paid recently": "Hawajalipa hivi karibuni",
  "Message": "Ujumbe",
  "Name (only you see this)": "Jina (unaliona wewe tu)",
  "New campaign": "Kampeni mpya",
  "No campaigns yet": "Hakuna kampeni bado",
  "No payment in this many days": "Hakuna malipo kwa siku hizi",
  "Nobody matched.": "Hakuna aliyelingana.",
  "October reconnect reminder": "Kikumbusho cha kurudisha huduma Oktoba",
  "Paid afterwards": "Walilipa baadaye",
  "Preview": "Onyesho",
  "Remind suspended customers, announce a new plan, or win back quiet ones.": "Wakumbushe wateja waliosimamishwa, tangaza mpango mpya, au warudishe walionyamaza.",
  "SMS each": "SMS kila mmoja",
  "Schedule this message for": "Panga ujumbe huu kwa",
  "Send by": "Tuma kwa",
  "Send now": "Tuma sasa",
  "Send one SMS or WhatsApp message to a group of customers, and see who paid in the days after.": "Tuma ujumbe mmoja wa SMS au WhatsApp kwa kundi la wateja, na uone nani alilipa siku zilizofuata.",
  "Send this message now to": "Tuma ujumbe huu sasa kwa",
  "Send to": "Tuma kwa",
  "Sending": "Inatuma",
  "Stop this campaign? Messages already sent stay sent.": "Simamisha kampeni hii? Ujumbe uliotumwa tayari unabaki umetumwa.",
  "Stopped": "Imesimamishwa",
  "The list of customers is made when sending starts.": "Orodha ya wateja huundwa kutuma kunapoanza.",
  "Up to": "Hadi",
  "When (leave empty to send now)": "Lini (acha wazi kutuma sasa)",
  "With an overdue bill": "Wenye bili iliyochelewa",
  "brought in": "zimeletwa",
  "customers": "wateja",
  "customers match right now.": "wateja wanalingana sasa hivi.",
  "customers paid afterwards": "wateja walilipa baadaye",
  "in total": "kwa jumla",
  "messages sent": "jumbe zimetumwa",
  "A place counts as covered when it is within this distance of one of your routers that has a location. Set router locations on the Routers page.": "Mahali huhesabiwa kuwa ndani ya huduma kikiwa ndani ya umbali huu kutoka ruta yako yenye mahali. Weka mahali pa ruta kwenye ukurasa wa Ruta.",
  "Assign a technician under Field work.": "Mpe fundi kazi chini ya Kazi za uwanjani.",
  "Became customers": "Wamekuwa wateja",
  "Book installation": "Panga usakinishaji",
  "Book survey": "Panga ukaguzi",
  "Booked": "Imepangwa",
  "Called": "Amepigiwa",
  "Copied": "Imenakiliwa",
  "Copy link": "Nakili kiungo",
  "Copy this link:": "Nakili kiungo hiki:",
  "Coverage": "Eneo la huduma",
  "Covered within, km": "Huduma ndani ya km",
  "In coverage": "Ndani ya huduma",
  "Location not shared": "Mahali hapajashirikiwa",
  "Lost": "Imepotea",
  "Make": "Mfanye",
  "Mark called": "Weka amepigiwa",
  "New": "Mpya",
  "No open requests": "Hakuna maombi yaliyo wazi",
  "Nothing here": "Hakuna kitu hapa",
  "Open customer": "Fungua mteja",
  "People who asked to be connected on your public signup page. Call them, then turn them into a customer with an installation job.": "Watu walioomba kuunganishwa kwenye ukurasa wako wa kujisajili. Wapigie simu, kisha uwafanye wateja pamoja na kazi ya usakinishaji.",
  "Share your signup page link to start getting requests.": "Shiriki kiungo cha ukurasa wako wa kujisajili ili kuanza kupata maombi.",
  "Show": "Onyesha",
  "Signup page is on": "Ukurasa wa kujisajili umewashwa",
  "Signup requests": "Maombi ya kuunganishwa",
  "Where": "Wapi",
  "Why was this request lost? (e.g. out of coverage, too expensive, no answer)": "Kwa nini ombi hili limepotea? (mf. nje ya huduma, ghali mno, hapokei simu)",
  "Your signup page:": "Ukurasa wako wa kujisajili:",
  "a customer and book a site survey first?": "kuwa mteja na upange ukaguzi wa eneo kwanza?",
  "a customer and book the installation?": "kuwa mteja na upange usakinishaji?",
  "created with job": "ameundwa pamoja na kazi",
  "from coverage": "kutoka eneo la huduma",
  "After your password, you also give a code from your phone, so a stolen password alone can't get into your account.": "Baada ya nenosiri lako, unatoa pia msimbo kutoka simu yako, hivyo nenosiri lililoibiwa pekee haliwezi kuingia kwenye akaunti yako.",
  "Get codes by SMS to": "Pata misimbo kwa SMS kwenye",
  "I've saved them": "Nimeihifadhi",
  "Make new ones soon.": "Tengeneza mipya hivi karibuni.",
  "New recovery codes": "Misimbo mipya ya dharura",
  "Off": "Imezimwa",
  "On: SMS": "Imewashwa: SMS",
  "On: authenticator app": "Imewashwa: programu ya uthibitishaji",
  "Recovery codes left:": "Misimbo ya dharura iliyobaki:",
  "Require two-step sign-in for all staff": "Lazimisha kuingia kwa hatua mbili kwa wafanyakazi wote",
  "Staff sign-in rules": "Sheria za kuingia kwa wafanyakazi",
  "Staff who haven't set it up are asked to at their next sign-in, before they can get in. Customers and agents aren't affected.": "Wafanyakazi ambao hawajaiweka wataombwa kuiweka wanapoingia tena, kabla ya kuingia. Wateja na mawakala hawaathiriki.",
  "Turn off": "Zima",
  "Turn off two-step sign-in?": "Zima kuingia kwa hatua mbili?",
  "Turn on": "Washa",
  "Two-step sign-in": "Kuingia kwa hatua mbili",
  "Use an authenticator app": "Tumia programu ya uthibitishaji",
  "We sent a 6-digit code to your phone ending": "Tumetuma msimbo wa tarakimu 6 kwenye simu yako inayoishia",
  "Your ISP requires two-step sign-in for staff. Set it up now, or you'll be asked to at your next sign-in.": "Mtoa huduma wako analazimisha kuingia kwa hatua mbili kwa wafanyakazi. Iweke sasa, au utaombwa kuiweka unapoingia tena.",
  "Your password": "Nenosiri lako",
};
