/**
 * Swahili for the dashboard pages that use tr(). Keys are the exact English text on the page;
 * a phrase missing here simply shows in English.
 */
export const SW: Record<string, string> = {
  "+ role": "+ jukumu",
  "0 turns the early reminder off.": "0 huzima ukumbusho wa mapema.",
  "A courtesy reminder while there is still time to pay.": "Ukumbusho wa heshima wakati bado kuna muda wa kulipa.",
  "A subdomain of a domain you own — not the bare platform domain.": "Kikoa kidogo cha kikoa unachomiliki, si kikoa cha jukwaa chenyewe.",
  "AI assistant": "Msaidizi wa AI",
  "API key": "Ufunguo wa API",
  "API tokens": "Tokeni za API",
  "API tokens for external clients, and webhooks for outbound event delivery.": "Tokeni za API kwa programu za nje, na webhooks za kutuma matukio nje.",
  "Account": "Akaunti",
  "Action": "Kitendo",
  "Actions": "Vitendo",
  "Active": "Hai",
  "Active Services": "Huduma Hai",
  "Active Subscribers": "Wateja Hai",
  "Active internet access": "Intaneti inayofanya kazi",
  "Add a colleague and give them a role that matches their job.": "Ongeza mwenzako na umpe jukumu linalolingana na kazi yake.",
  "Add a role": "Ongeza jukumu",
  "Add customer": "Ongeza mteja",
  "Add package": "Ongeza kifurushi",
  "Add time": "Ongeza muda",
  "Add your first package": "Ongeza kifurushi chako cha kwanza",
  "Address": "Anwani",
  "All Time": "Muda Wote",
  "All branches": "Matawi yote",
  "All vouchers": "Vocha zote",
  "Already done:": "Tayari imefanyika:",
  "Amount": "Kiasi",
  "Amount (KES)": "Kiasi (KES)",
  "Analytics": "Takwimu",
  "Anthropic API key": "Ufunguo wa API wa Anthropic",
  "Apply": "Tumia",
  "Apply payment to an invoice": "Weka malipo kwenye ankara",
  "Apply to invoice": "Weka kwenye ankara",
  "Assigned": "Aliyepewa",
  "At least 10 characters, with a letter and a digit or symbol.": "Angalau herufi 10, zikiwemo herufi na tarakimu au alama.",
  "Attempted": "Ilijaribiwa",
  "Automation": "Otomatiki",
  "Average Spend / User": "Wastani wa Matumizi / Mtumiaji",
  "Average lifetime spend": "Wastani wa matumizi yote",
  "Average per subscriber": "Wastani kwa kila mteja",
  "Average spend in period": "Wastani wa matumizi katika kipindi",
  "Avg Spend / Client": "Wastani / Mteja",
  "Awaiting approval": "Inasubiri idhini",
  "Bandwidth Usage": "Matumizi ya Data",
  "Bandwidth telemetry recorded across your routers.": "Takwimu za data zilizorekodiwa kwenye ruta zako zote.",
  "Based on": "Kulingana na",
  "Before the due date": "Kabla ya tarehe ya mwisho",
  "Billing Frequency": "Mzunguko wa Malipo",
  "Block sharing over a phone hotspot": "Zuia kushiriki kupitia hotspot ya simu",
  "Bot Test": "Jaribio la Bot",
  "Branch": "Tawi",
  "Branch name": "Jina la tawi",
  "Branches": "Matawi",
  "Branding and contact": "Chapa na mawasiliano",
  "Cancel": "Ghairi",
  "Captive Portal Studio": "Studio ya Ukurasa wa Kuingia",
  "Checked": "Imekaguliwa",
  "Choose a role…": "Chagua jukumu…",
  "Client": "Mteja",
  "Client Directory & Spend History": "Orodha ya Wateja na Historia ya Matumizi",
  "Client Name": "Jina la Mteja",
  "Clients & Spends": "Wateja na Matumizi",
  "Code": "Msimbo",
  "Collections, settlements and reconciliation": "Makusanyo, malipo na upatanisho",
  "Completed payments, in your timezone": "Malipo yaliyokamilika, kwa saa za eneo lako",
  "Configure DNS": "Sanidi DNS",
  "Confirm new password": "Thibitisha nenosiri jipya",
  "Copy": "Nakili",
  "Create Broadband Plan": "Unda Mpango wa Intaneti",
  "Create your first bandwidth subscription plan above.": "Unda mpango wako wa kwanza wa intaneti hapo juu.",
  "Cumulative customer LTV": "Jumla ya thamani ya wateja",
  "Current Plan": "Mpango wa Sasa",
  "Current password": "Nenosiri la sasa",
  "Custom Domain": "Kikoa Maalum",
  "Custom Range": "Kipindi Maalum",
  "Custom limits (no package)": "Mipaka maalum (bila kifurushi)",
  "Customer": "Mteja",
  "Customer phone, e.g. 254712345678": "Simu ya mteja, mf. 254712345678",
  "Customers": "Wateja",
  "Customers at risk": "Wateja walio hatarini",
  "Customers can tap to call it.": "Wateja wanaweza kugusa kupiga simu.",
  "Customers see these on the Wi-Fi sign-in page and pay for them with M-Pesa.": "Wateja huona hivi kwenye ukurasa wa kuingia Wi-Fi na hulipa kwa M-Pesa.",
  "Custom…": "Maalum…",
  "Dashboard colours": "Rangi za dashibodi",
  "Data": "Data",
  "Data limit (MB)": "Kikomo cha data (MB)",
  "Data used per day": "Data iliyotumika kwa siku",
  "Date & Time": "Tarehe na Saa",
  "Days before due date": "Siku kabla ya tarehe ya mwisho",
  "Delete": "Futa",
  "Describe the packages you want in plain words, and it creates or edits them for you.": "Eleza vifurushi unavyotaka kwa maneno ya kawaida, nao utaviunda au kuvihariri.",
  "Description (optional)": "Maelezo (si lazima)",
  "Design": "Muundo",
  "Detailed payment records with receipt numbers, client details, and M-Pesa references.": "Rekodi kamili za malipo zenye namba za risiti, maelezo ya mteja na kumbukumbu za M-Pesa.",
  "Developer": "Msanidi",
  "Devices": "Vifaa",
  "Devices per voucher": "Vifaa kwa kila vocha",
  "Dismiss": "Funga",
  "Domain": "Kikoa",
  "Domain Management": "Usimamizi wa Kikoa",
  "Download (Mbps)": "Kupakua (Mbps)",
  "Download (Rx)": "Kupakua (Rx)",
  "Download Speed (Kbps)": "Kasi ya Kupakua (Kbps)",
  "Download and upload": "Kupakua na kupakia",
  "Download and upload across all your routers.": "Kupakua na kupakia kwenye ruta zako zote.",
  "Download speed (Mbps)": "Kasi ya kupakua (Mbps)",
  "Downloaded": "Iliyopakuliwa",
  "Edit": "Hariri",
  "Email": "Barua pepe",
  "Email body": "Maandishi ya barua pepe",
  "Email subject": "Kichwa cha barua pepe",
  "Embed a Tawk.to chat widget for staff and/or hotspot customers.": "Weka kisanduku cha gumzo cha Tawk.to kwa wafanyakazi na/au wateja wa hotspot.",
  "Enabled": "Imewashwa",
  "Endpoint URL": "URL ya kupokea",
  "Enter this code on your phone": "Weka msimbo huu kwenye simu yako",
  "Event": "Tukio",
  "Events": "Matukio",
  "Every active customer is paid up and paying regularly.": "Kila mteja hai amelipa na analipa mara kwa mara.",
  "Every completed payment is on an invoice. Nothing to do here.": "Kila malipo yaliyokamilika yako kwenye ankara. Hakuna la kufanya hapa.",
  "Every hotspot and PPPoE session, with the customer and their last payment behind it. Updates every 20 seconds.": "Kila kipindi cha hotspot na PPPoE, pamoja na mteja na malipo yake ya mwisho. Husasishwa kila sekunde 20.",
  "Everyone who bought a package on your hotspot portal, and how much they've used.": "Kila aliyenunua kifurushi kwenye hotspot yako, na kiasi alichotumia.",
  "Everything is matched": "Kila kitu kimelinganishwa",
  "Expires": "Inaisha",
  "Export CSV": "Hamisha CSV",
  "Export Clients CSV": "Hamisha Wateja CSV",
  "FUP Status": "Hali ya FUP",
  "Failing": "Inashindwa",
  "Fast, reliable Wi-Fi": "Wi-Fi ya kasi na ya kuaminika",
  "Final notice": "Ilani ya mwisho",
  "Find a code": "Tafuta msimbo",
  "From": "Kuanzia",
  "Full access (same permissions as your account)": "Ruhusa kamili (sawa na akaunti yako)",
  "Gross completed payments": "Jumla ya malipo yaliyokamilika",
  "Growth, what sells, when customers pay, and who is at risk of leaving.": "Ukuaji, kinachouzika, wateja hulipa lini, na nani yuko hatarini kuondoka.",
  "Hardware orders": "Maagizo ya vifaa",
  "Heading": "Kichwa",
  "Highlight on the portal": "Angazia kwenye ukurasa",
  "Home and business lines": "Laini za nyumbani na biashara",
  "Home branch (optional)": "Tawi la nyumbani (si lazima)",
  "Home internet sales number": "Namba ya mauzo ya intaneti ya nyumbani",
  "Hotspot": "Hotspot",
  "Hotspot Vouchers": "Vocha za Hotspot",
  "Hotspot captive portal (customer-facing)": "Ukurasa wa kuingia hotspot (kwa wateja)",
  "Hotspot online": "Hotspot mtandaoni",
  "Hotspot sections": "Sehemu za hotspot",
  "Hours a new ticket may wait for its first reply before it shows as overdue on the Tickets page.": "Saa ambazo tiketi mpya inaweza kusubiri jibu la kwanza kabla ya kuonekana imechelewa kwenye ukurasa wa Tiketi.",
  "How many": "Ngapi",
  "How the sign-in page looks. MashupHost Clean loads fastest on phones.": "Jinsi ukurasa wa kuingia unavyoonekana. MashupHost Clean hufunguka haraka zaidi kwenye simu.",
  "ISPs": "Watoa huduma",
  "ISPs on the platform": "Watoa huduma kwenye jukwaa",
  "If you run in one area only, you do not need any.": "Ukifanya kazi eneo moja tu, huhitaji tawi lolote.",
  "Installation fee": "Ada ya ufungaji",
  "Internal note (not visible to the customer)": "Dokezo la ndani (mteja haoni)",
  "Invoice number, customer name or phone": "Namba ya ankara, jina la mteja au simu",
  "Joined This Month": "Walijiunga Mwezi Huu",
  "Joined This Week": "Walijiunga Wiki Hii",
  "Joined Today": "Walijiunga Leo",
  "Joined When": "Alijiunga Lini",
  "Joined:": "Alijiunga:",
  "Key name": "Jina la ufunguo",
  "Label": "Lebo",
  "Last 14 Days": "Siku 14 Zilizopita",
  "Last 30 Days": "Siku 30 Zilizopita",
  "Last 7 Days": "Siku 7 Zilizopita",
  "Last payment": "Malipo ya mwisho",
  "Last sign-in": "Kuingia mara ya mwisho",
  "Lasts": "Hudumu",
  "Lasts (minutes)": "Hudumu (dakika)",
  "Latest Receipt": "Risiti ya Karibuni",
  "Lets you manage hotspot packages by describing changes in plain language, from the Hotspot Vouchers page.": "Hukuwezesha kusimamia vifurushi vya hotspot kwa kueleza mabadiliko kwa lugha ya kawaida, kutoka ukurasa wa Vocha za Hotspot.",
  "Link a Device": "Unganisha Kifaa",
  "Link a router": "Unganisha ruta",
  "Link router": "Unganisha ruta",
  "Link with phone number": "Unganisha kwa namba ya simu",
  "Link your first MikroTik": "Unganisha MikroTik yako ya kwanza",
  "Link your own WhatsApp number to send vouchers and answer customers automatically.": "Unganisha namba yako ya WhatsApp ili kutuma vocha na kujibu wateja kiotomatiki.",
  "Linked Devices": "Vifaa Vilivyounganishwa",
  "Linked number": "Namba iliyounganishwa",
  "Linking a router generates a setup script for it, with its own RADIUS secret.": "Kuunganisha ruta hutengeneza hati ya usanidi wake, yenye siri yake ya RADIUS.",
  "Live chat": "Gumzo la moja kwa moja",
  "Loading client tracker...": "Inapakia wateja...",
  "Loading daily telemetry...": "Inapakia takwimu za kila siku...",
  "Loading domains...": "Inapakia vikoa...",
  "Loading packages...": "Inapakia vifurushi...",
  "Loading packages…": "Inapakia vifurushi…",
  "Loading sales…": "Inapakia mauzo…",
  "Loading subscription...": "Inapakia usajili...",
  "Loading ticket...": "Inapakia tiketi...",
  "Loading tickets...": "Inapakia tiketi...",
  "Loading transactions ledger...": "Inapakia miamala...",
  "Loading vouchers…": "Inapakia vocha…",
  "Loading...": "Inapakia...",
  "Loading…": "Inapakia…",
  "Location (optional)": "Mahali (si lazima)",
  "M-Pesa Phone Number": "Namba ya Simu ya M-Pesa",
  "Made": "Zilizotengenezwa",
  "Make vouchers": "Tengeneza vocha",
  "Manage": "Simamia",
  "Manage tenants": "Simamia watoa huduma",
  "Messages": "Ujumbe",
  "Method": "Njia",
  "Method & Ref": "Njia na Kumbukumbu",
  "Minutes": "Dakika",
  "Model": "Modeli",
  "Money waiting": "Pesa inayosubiri",
  "Monthly internet plans for PPPoE subscribers: speed and price.": "Mipango ya intaneti ya kila mwezi kwa wateja wa PPPoE: kasi na bei.",
  "Most popular": "Maarufu zaidi",
  "My Subscription": "Usajili Wangu",
  "Name": "Jina",
  "Name on the portal": "Jina kwenye ukurasa",
  "Name, phone, voucher, IP or MAC": "Jina, simu, vocha, IP au MAC",
  "Needs at least one available Claude model on your account.": "Inahitaji angalau modeli moja ya Claude kwenye akaunti yako.",
  "Network map": "Ramani ya mtandao",
  "New password": "Nenosiri jipya",
  "Next": "Ifuatayo",
  "Next step": "Hatua inayofuata",
  "No ISPs yet": "Bado hakuna watoa huduma",
  "No VLANs yet": "Bado hakuna VLAN",
  "No branches yet": "Bado hakuna matawi",
  "No clients found matching the selected timeframe or search criteria.": "Hakuna wateja wanaolingana na kipindi au utafutaji uliochaguliwa.",
  "No custom domain connected": "Hakuna kikoa maalum kilichounganishwa",
  "No deliveries yet.": "Bado hakuna utumaji.",
  "No limit": "Bila kikomo",
  "No open invoices match.": "Hakuna ankara wazi zinazolingana.",
  "No package sales in this period.": "Hakuna mauzo ya vifurushi katika kipindi hiki.",
  "No packages defined": "Hakuna vifurushi vilivyowekwa",
  "No packages yet": "Bado hakuna vifurushi",
  "No payments in this period": "Hakuna malipo katika kipindi hiki",
  "No payments yet": "Bado hakuna malipo",
  "No revenue records found for this period or search criteria.": "Hakuna rekodi za mapato kwa kipindi au utafutaji huu.",
  "No routers linked yet": "Bado hakuna ruta zilizounganishwa",
  "No routers yet": "Bado hakuna ruta",
  "No sales yet": "Bado hakuna mauzo",
  "No tickets here": "Hakuna tiketi hapa",
  "No tokens yet.": "Bado hakuna tokeni.",
  "No webhook endpoints yet.": "Bado hakuna webhooks.",
  "Nobody at risk right now": "Hakuna aliye hatarini sasa",
  "None on record": "Hakuna kwenye rekodi",
  "None yet": "Bado hakuna",
  "Not a known customer or voucher": "Si mteja wala vocha inayojulikana",
  "Not a secret — this is meant to be visible in the page, same as on any website.": "Si siri: inakusudiwa kuonekana kwenye ukurasa, kama kwenye tovuti yoyote.",
  "Not connected yet": "Bado haijaunganishwa",
  "Nothing matches this filter right now.": "Hakuna kinacholingana na kichujio hiki sasa.",
  "Offline": "Nje ya mtandao",
  "On portal": "Kwenye ukurasa",
  "Once overdue": "Ikishachelewa",
  "Online": "Mtandaoni",
  "Online and paid": "Mtandaoni na wamelipa",
  "Online users": "Watumiaji mtandaoni",
  "Only you so far": "Wewe peke yako kwa sasa",
  "Open": "Wazi",
  "Open Studio": "Fungua Studio",
  "Or link with a phone number": "Au unganisha kwa namba ya simu",
  "Other services": "Huduma nyingine",
  "Overdue": "Imechelewa",
  "Owed": "Deni",
  "PPPoE online": "PPPoE mtandaoni",
  "Package": "Kifurushi",
  "Package Name": "Jina la Kifurushi",
  "Package assistant": "Msaidizi wa vifurushi",
  "Packages": "Vifurushi",
  "Packages customers buy with M-Pesa, cash vouchers, and the Wi-Fi sign-in page they see.": "Vifurushi wateja hununua kwa M-Pesa, vocha za pesa taslimu, na ukurasa wa kuingia Wi-Fi wanaouona.",
  "Paid": "Imelipwa",
  "Paid by": "Imelipwa na",
  "Password": "Nenosiri",
  "Pay with M-Pesa and connect instantly": "Lipa kwa M-Pesa na uunganishwe papo hapo",
  "Paying Clients": "Wateja Wanaolipa",
  "Payment History": "Historia ya Malipo",
  "Payments": "Malipo",
  "Payments that arrived without an invoice to settle. Apply each one to the right invoice so the customer's balance and service are correct.": "Malipo yaliyofika bila ankara ya kulipia. Weka kila moja kwenye ankara sahihi ili salio na huduma ya mteja viwe sawa.",
  "Period": "Kipindi",
  "Period:": "Kipindi:",
  "Person": "Mtu",
  "Phone": "Simu",
  "Phone (MAC)": "Simu (MAC)",
  "Phone (optional)": "Simu (si lazima)",
  "Phones on your hotspot are sent here automatically. You can also share it.": "Simu kwenye hotspot yako huletwa hapa kiotomatiki. Unaweza pia kuushiriki.",
  "Plan": "Mpango",
  "Platform status": "Hali ya jukwaa",
  "Portal add-ons: announcements, social links, ads, live chat and other extras on the sign-in page.": "Nyongeza za ukurasa: matangazo, viungo vya mitandao ya kijamii, gumzo na zaidi kwenye ukurasa wa kuingia.",
  "Portal preview": "Hakikisho la ukurasa",
  "Prepaid voucher": "Vocha ya kulipia kabla",
  "Preparing your QR code…": "Inaandaa msimbo wako wa QR…",
  "Previous": "Iliyotangulia",
  "Price": "Bei",
  "Price (KES)": "Bei (KES)",
  "Price (KES, e.g. 2500.00)": "Bei (KES, mf. 2500.00)",
  "Price (KSh)": "Bei (KSh)",
  "Primary": "Kuu",
  "Print": "Chapisha",
  "Print / PDF Report": "Chapisha / Ripoti ya PDF",
  "Print / Save PDF": "Chapisha / Hifadhi PDF",
  "Printable codes you sell for cash. Each one works once, for the time and limits below.": "Misimbo ya kuchapisha unayouza kwa pesa taslimu. Kila mmoja hufanya kazi mara moja, kwa muda na mipaka iliyo hapa chini.",
  "Priority": "Kipaumbele",
  "Profile": "Wasifu",
  "Provisioning": "Usanidi",
  "Published. Customers see it now.": "Imechapishwa. Wateja wanaiona sasa.",
  "Purchases made on your hotspot portal appear here.": "Manunuzi kwenye hotspot yako yanaonekana hapa.",
  "Querying top consumers...": "Inatafuta watumiaji wakubwa...",
  "RADIUS Data Accounting": "Hesabu ya Data ya RADIUS",
  "Receipt": "Risiti",
  "Receipt #": "Risiti #",
  "Receipts generated": "Risiti zilizotolewa",
  "Received": "Imepokelewa",
  "Received but not yet on an invoice": "Imepokelewa lakini bado haiko kwenye ankara",
  "Recommended": "Inapendekezwa",
  "Reconciliation": "Upatanisho",
  "Reconnecting later needs a new QR scan.": "Kuunganisha tena baadaye kunahitaji kuchanganua QR upya.",
  "Recorded by RADIUS": "Imerekodiwa na RADIUS",
  "Reference": "Kumbukumbu",
  "Refreshes every minute": "Husasishwa kila dakika",
  "Reminders and tickets": "Vikumbusho na tiketi",
  "Remove": "Ondoa",
  "Rename": "Badilisha jina",
  "Renew Now": "Fanya Upya Sasa",
  "Replied": "Imejibiwa",
  "Reports": "Ripoti",
  "Requests from subscribers, hotspot walk-ins, and staff — reply, assign, and track to resolution.": "Maombi kutoka kwa wateja, watumiaji wa hotspot na wafanyakazi: jibu, kabidhi na fuatilia hadi yatatuliwe.",
  "Response": "Jibu",
  "Restore access": "Rejesha huduma",
  "Reveal secret": "Onyesha siri",
  "Revenue & Financials": "Mapato na Fedha",
  "Revenue Breakdown by Payment Channel": "Mapato kwa Njia ya Malipo",
  "Revenue by month": "Mapato kwa mwezi",
  "Revenue per day, last 30 days": "Mapato kwa siku, siku 30 zilizopita",
  "Revenue per month": "Mapato kwa mwezi",
  "Revenue will be charted here as payments come in.": "Mapato yataonyeshwa hapa malipo yanapoingia.",
  "Revenue, customer spending and bandwidth, with receipts and exports.": "Mapato, matumizi ya wateja na data, pamoja na risiti na uhamishaji.",
  "Revoke": "Batilisha",
  "Revoked": "Imebatilishwa",
  "Role": "Jukumu",
  "Roles": "Majukumu",
  "Router": "Ruta",
  "Router map": "Ramani ya ruta",
  "Routers": "Ruta",
  "Sales": "Mauzo",
  "Saved": "Imehifadhiwa",
  "Scan this from the phone you want to connect": "Changanua hii kwa simu unayotaka kuunganisha",
  "Schedule": "Ratiba",
  "Scope": "Wigo",
  "Search client name, phone or #...": "Tafuta jina la mteja, simu au #...",
  "Search receipt, client or M-Pesa ref...": "Tafuta risiti, mteja au kumbukumbu ya M-Pesa...",
  "Search subscriber username...": "Tafuta jina la mtumiaji...",
  "Send a message to test the bot.": "Tuma ujumbe kujaribu bot.",
  "Send by SMS": "Tuma kwa SMS",
  "Send by WhatsApp": "Tuma kwa WhatsApp",
  "Send by email": "Tuma kwa barua pepe",
  "Send test": "Tuma jaribio",
  "Sent the day before the connection is suspended.": "Hutumwa siku moja kabla ya huduma kusimamishwa.",
  "Sent the day the invoice becomes overdue.": "Hutumwa siku ankara inapochelewa.",
  "Service": "Huduma",
  "Service / Description": "Huduma / Maelezo",
  "Sessions": "Vipindi",
  "Sessions appear here as soon as a router reports them over RADIUS accounting.": "Vipindi huonekana hapa mara ruta inapoviripoti kupitia hesabu ya RADIUS.",
  "Set up your account": "Andaa akaunti yako",
  "Settings": "Mipangilio",
  "Share it with them privately. They can change it under Settings → Password.": "Mpe kwa faragha. Anaweza kulibadilisha kwenye Mipangilio → Nenosiri.",
  "Shown to every customer on the Wi-Fi sign-in page.": "Huonyeshwa kwa kila mteja kwenye ukurasa wa kuingia Wi-Fi.",
  "Shown with home internet (fibre) offers.": "Huonyeshwa pamoja na ofa za intaneti ya nyumbani (fibre).",
  "Sign in to an ISP account to edit its portal.": "Ingia kwenye akaunti ya mtoa huduma ili kuhariri ukurasa wake.",
  "Signing secret": "Siri ya kusaini",
  "Since": "Tangu",
  "Site": "Eneo",
  "Source": "Chanzo",
  "Speed": "Kasi",
  "Staff": "Wafanyakazi",
  "Staff and roles": "Wafanyakazi na majukumu",
  "Staff dashboard": "Dashibodi ya wafanyakazi",
  "Start Chat": "Anza Gumzo",
  "Static IP and IPTV": "IP ya kudumu na IPTV",
  "Status": "Hali",
  "Stops one buyer re-sharing this package to other devices. Can also block legitimate travel routers.": "Huzuia mnunuzi mmoja kushiriki kifurushi hiki na vifaa vingine. Inaweza pia kuzuia ruta halali za safari.",
  "Store prices": "Bei za duka",
  "Subheading": "Kichwa kidogo",
  "Subject": "Mada",
  "Subnet": "Subnet",
  "Subscriber Username": "Jina la Mtumiaji",
  "Subscribers in view": "Wateja wanaoonekana",
  "Subscribers who used the most data, PPPoE and hotspot.": "Wateja waliotumia data nyingi zaidi, PPPoE na hotspot.",
  "Subscriptions off for non-payment": "Huduma zilizozimwa kwa kutolipa",
  "Support number": "Namba ya msaada",
  "Support response targets": "Malengo ya muda wa kujibu",
  "Support tickets": "Tiketi za msaada",
  "Suspend": "Simamisha",
  "Suspended": "Imesimamishwa",
  "Suspended, overdue, or a paying customer who has gone quiet. Call them before they leave.": "Waliosimamishwa, waliochelewa, au mteja aliyekuwa analipa na amenyamaza. Wapigie kabla hawajaondoka.",
  "Tagged network segments and their provisioning status": "Sehemu za mtandao zilizowekwa lebo na hali ya usanidi wake",
  "Target": "Lengo",
  "Tawk.to widget ID": "Kitambulisho cha Tawk.to",
  "Temporary password": "Nenosiri la muda",
  "Test Bot": "Jaribu Bot",
  "The latest 100.": "100 za karibuni.",
  "The ten most recent tenants": "Watoa huduma kumi wa karibuni",
  "The towns or areas you run. Put routers, customers and staff in a branch to filter lists and analytics by it.": "Miji au maeneo unayohudumia. Weka ruta, wateja na wafanyakazi kwenye tawi ili kuchuja orodha na takwimu kwa tawi hilo.",
  "This Month": "Mwezi Huu",
  "This Week": "Wiki Hii",
  "This month": "Mwezi huu",
  "This takes a few seconds.": "Hii huchukua sekunde chache.",
  "Three messages go out at most: before the due date, once overdue, and the day before suspension. Each is sent once per invoice.": "Ujumbe usiozidi mitatu hutumwa: kabla ya tarehe ya mwisho, ikishachelewa, na siku moja kabla ya kusimamishwa. Kila mmoja hutumwa mara moja kwa kila ankara.",
  "Today (Day)": "Leo (Siku)",
  "Total Client Spend": "Jumla ya Matumizi ya Wateja",
  "Total Clients": "Jumla ya Wateja",
  "Total Data": "Jumla ya Data",
  "Total Revenue": "Jumla ya Mapato",
  "Total Spends (KES)": "Jumla ya Matumizi (KES)",
  "Total data": "Jumla ya data",
  "Track when subscribers joined, their lifetime spending, and view receipts.": "Fuatilia wateja walijiunga lini, matumizi yao yote, na uone risiti.",
  "Transactions": "Miamala",
  "Transactions & Stamped Receipts": "Miamala na Risiti Zilizogongwa Muhuri",
  "Type": "Aina",
  "Type a message...": "Andika ujumbe...",
  "Unique subscribers & guests": "Wateja na wageni tofauti",
  "Unknown payer": "Mlipaji asiyejulikana",
  "Unlimited": "Bila kikomo",
  "Unlocks": "Hufungua",
  "Unmatched payments": "Malipo yasiyolinganishwa",
  "Update speed tiers and monthly pricing.": "Sasisha viwango vya kasi na bei za kila mwezi.",
  "Updated": "Imesasishwa",
  "Upload (Mbps)": "Kupakia (Mbps)",
  "Upload (Tx)": "Kupakia (Tx)",
  "Upload Speed (Kbps)": "Kasi ya Kupakia (Kbps)",
  "Upload speed (Mbps)": "Kasi ya kupakia (Mbps)",
  "Uploaded": "Iliyopakiwa",
  "Used": "Imetumika",
  "VLANs": "VLAN",
  "View all": "Tazama zote",
  "Voucher": "Vocha",
  "Voucher and account logins": "Kuingia kwa vocha na akaunti",
  "Webhooks": "Webhooks",
  "What customers can buy on your hotspot portal.": "Wateja wanachoweza kununua kwenye hotspot yako.",
  "What customers can buy on your hotspot. Switched-off packages stay here but don't show on the portal.": "Wateja wanachoweza kununua kwenye hotspot yako. Vifurushi vilivyozimwa hubaki hapa lakini havionekani kwenye ukurasa.",
  "What each role can do": "Kila jukumu linaweza kufanya nini",
  "What it can do": "Kinachoweza kufanya",
  "What it unlocks": "Kinachofungua",
  "What sells": "Kinachouzika",
  "What this number now does": "Namba hii sasa inafanya nini",
  "WhatsApp": "WhatsApp",
  "WhatsApp messages use the SMS wording and go out from the number linked under Settings → WhatsApp. Without a linked number they are skipped.": "Ujumbe wa WhatsApp hutumia maneno ya SMS na hutoka kwenye namba iliyounganishwa kwenye Mipangilio → WhatsApp. Bila namba iliyounganishwa hurukwa.",
  "When customers are reminded to pay, what the messages say, and how fast support must answer.": "Wateja hukumbushwa kulipa lini, ujumbe unasema nini, na msaada lazima ujibu kwa haraka gani.",
  "When customers pay": "Wateja hulipa lini",
  "Where it shows": "Mahali kinaonekana",
  "Where your routers are and which ones are reporting. Click a router in the list, then click the map to place it.": "Ruta zako ziko wapi na zipi zinaripoti. Bofya ruta kwenye orodha, kisha bofya ramani kuiweka.",
  "Who": "Nani",
  "Who can sign in to this dashboard, and what each person may do.": "Nani anaweza kuingia kwenye dashibodi hii, na kila mtu anaruhusiwa kufanya nini.",
  "Why": "Sababu",
  "Widget ID": "Kitambulisho cha kisanduku",
  "Write a reply...": "Andika jibu...",
  "Your Platform Domain": "Kikoa Chako cha Jukwaa",
  "Your business name": "Jina la biashara yako",
  "Your current plan, usage, and renewal history.": "Mpango wako wa sasa, matumizi, na historia ya kufanya upya.",
  "Your customers are being messaged from a shared number": "Wateja wako wanatumiwa ujumbe kutoka namba ya pamoja",
  "Your platform subdomain always works — connect a custom domain if you want your own branded URL.": "Kikoa kidogo chako cha jukwaa hufanya kazi daima. Unganisha kikoa maalum ukitaka URL yenye chapa yako.",
  "Your portal link": "Kiungo cha ukurasa wako",
  "Your profile and sign-in security.": "Wasifu wako na usalama wa kuingia.",
  "anything a customer replies there is discarded": "jibu lolote la mteja pale hutupwa",
  "e.g. 1 hour": "mf. saa 1",
  "e.g. Fiber Premium 20Mbps": "mf. Fiber Premium 20Mbps",
  "e.g. KSh 1,500": "mf. KSh 1,500",
  "e.g. Kasarani": "mf. Kasarani",
  "e.g. Nairobi, Thika Road": "mf. Nairobi, Thika Road",
  "e.g. Sync payments to our accounting system": "mf. Sawazisha malipo na mfumo wetu wa hesabu",
  "e.g. claude-desktop — so you know which one to revoke": "mf. claude-desktop, ili ujue upi wa kubatilisha",
  "to": "hadi",
  "you": "wewe",
  "• Answers customers with a self-service menu (balance, buy Wi-Fi, report an outage, support)": "• Hujibu wateja kwa menyu ya kujihudumia (salio, nunua Wi-Fi, ripoti hitilafu, msaada)",

  "Suspended for non-payment": "Imesimamishwa kwa kutolipa",
  "Invoice overdue": "Ankara imechelewa",
  "No payment in over 40 days": "Hakuna malipo kwa zaidi ya siku 40",
  "Sunday": "Jumapili",
  "Monday": "Jumatatu",
  "Tuesday": "Jumanne",
  "Wednesday": "Jumatano",
  "Thursday": "Alhamisi",
  "Friday": "Ijumaa",
  "Saturday": "Jumamosi",
  "Send alert": "Tuma arifa",
  "% of their data cap in 30 days": "% ya kikomo chao cha data kwa siku 30",
  "1 day before": "Siku 1 kabla",
  "12 hours before": "Saa 12 kabla",
  "2 days before": "Siku 2 kabla",
  "2 hours before": "Saa 2 kabla",
  "A referrer with no active plan to extend gets the account credit instead.": "Aliyeleta mteja asiye na mpango hai wa kuongezewa hupata salio la akaunti badala yake.",
  "Account credit (KES):": "Salio la akaunti (KES):",
  "Add": "Ongeza",
  "Address or landmark": "Anwani au alama ya karibu",
  "All customers": "Wateja wote",
  "All jobs": "Kazi zote",
  "An installation needs the customer's signature before it can be closed.": "Ufungaji unahitaji sahihi ya mteja kabla ya kufungwa.",
  "Applied": "Imetekelezwa",
  "Before VAT": "Kabla ya VAT",
  "Call": "Piga simu",
  "Cancel job": "Ghairi kazi",
  "Cancel this job?": "Ghairi kazi hii?",
  "Cancel this maintenance? Customers already told will get a text saying it is off.": "Ghairi matengenezo haya? Wateja walioambiwa watapokea ujumbe kwamba yameahirishwa.",
  "Cancelled": "Imeghairiwa",
  "Cancelled.": "Imeghairiwa.",
  "Cancelled. Customers told:": "Imeghairiwa. Wateja walioarifiwa:",
  "Choose a branch.": "Chagua tawi.",
  "Choose a branch…": "Chagua tawi…",
  "Choose at least one router.": "Chagua angalau ruta moja.",
  "Clear": "Futa",
  "Close job": "Funga kazi",
  "Close the job": "Funga kazi",
  "Closed": "Imefungwa",
  "Contact phone": "Simu ya mawasiliano",
  "Create a job and assign it to a technician. They get an alert on their phone.": "Unda kazi na umpe fundi. Atapata arifa kwenye simu yake.",
  "Create job": "Unda kazi",
  "Customer (optional)": "Mteja (si lazima)",
  "Customer signature": "Sahihi ya mteja",
  "Customers on a router are those whose plan runs on it or who connected through it in the last 30 days.": "Wateja wa ruta ni wale ambao mpango wao uko juu yake au waliounganishwa kupitia hiyo siku 30 zilizopita.",
  "Customers told": "Wateja wameambiwa",
  "Customers who will be texted:": "Wateja watakaotumiwa ujumbe:",
  "Date": "Tarehe",
  "Dismissed": "Imekataliwa",
  "Dismissed.": "Imekataliwa.",
  "Done": "Imekamilika",
  "Ends": "Inaisha",
  "Equipment fitted": "Vifaa vilivyofungwa",
  "Every customer has a referral code. Enter it when you add a new customer; once the new customer pays for the first time, the one who referred them is rewarded.": "Kila mteja ana msimbo wa rufaa. Uweke unapoongeza mteja mpya; mteja mpya akilipa mara ya kwanza, aliyemleta anazawadiwa.",
  "Everyone": "Kila mtu",
  "Extra line for customers (optional)": "Ujumbe wa ziada kwa wateja (si lazima)",
  "Field work": "Kazi za uwanjani",
  "Finished": "Imemalizika",
  "For your team. Customers see the time and the extra line below.": "Kwa timu yako. Wateja huona muda na ujumbe wa ziada ulio hapa chini.",
  "Free days on their plan:": "Siku za bure kwenye mpango wao:",
  "Has referred": "Amewaleta",
  "Hotspot and voucher sales": "Mauzo ya hotspot na vocha",
  "I have arrived, start the job": "Nimefika, anza kazi",
  "In progress": "Inaendelea",
  "Installation": "Ufungaji",
  "Installations, repairs and site visits. Open a job on your phone to start it, add photos and close it with the customer's signature.": "Ufungaji, marekebisho na ziara za eneo. Fungua kazi kwenye simu yako ili kuianza, ongeza picha na uifunge kwa sahihi ya mteja.",
  "Invoice": "Ankara",
  "Invoiced subscriptions": "Usajili uliotolewa ankara",
  "Invoices": "Ankara",
  "Job photo": "Picha ya kazi",
  "Jobs assigned to you appear here.": "Kazi ulizopewa zinaonekana hapa.",
  "KRA PIN": "PIN ya KRA",
  "KRA PIN not set": "PIN ya KRA haijawekwa",
  "Look for subscribers who need a bigger plan": "Tafuta wateja wanaohitaji mpango mkubwa zaidi",
  "Maintenance": "Matengenezo",
  "Maintenance you schedule appears here.": "Matengenezo unayopanga yanaonekana hapa.",
  "Mine": "Zangu",
  "Month": "Mwezi",
  "Name of the person signing": "Jina la anayesaini",
  "New customer": "Mteja mpya",
  "New job": "Kazi mpya",
  "No customer yet": "Bado hakuna mteja",
  "No finished jobs": "Hakuna kazi zilizokamilika",
  "No invoice; prices include VAT at your standard rate.": "Hakuna ankara; bei zinajumuisha VAT kwa kiwango chako cha kawaida.",
  "No invoices this month": "Hakuna ankara mwezi huu",
  "No invoices this month.": "Hakuna ankara mwezi huu.",
  "No open jobs": "Hakuna kazi zilizo wazi",
  "No photos.": "Hakuna picha.",
  "No rewards yet": "Bado hakuna zawadi",
  "No time set": "Muda haujawekwa",
  "Nobody needs a bigger plan right now": "Hakuna anayehitaji mpango mkubwa sasa",
  "Not assigned": "Hajapewa mtu",
  "Notes for the technician": "Maelezo kwa fundi",
  "Nothing planned": "Hakuna kilichopangwa",
  "Nothing to do": "Hakuna la kufanya",
  "Now": "Sasa",
  "On site": "Yuko eneo la kazi",
  "Open in Maps": "Fungua kwenye Ramani",
  "Output VAT": "VAT ya mauzo",
  "Photos": "Picha",
  "Photos are shrunk on the phone before upload, so they send quickly on mobile data.": "Picha hupunguzwa ukubwa kwenye simu kabla ya kutumwa, hivyo hutumwa haraka kwa data ya simu.",
  "Plan upgrades": "Kuongeza vifurushi",
  "Planned maintenance": "Matengenezo yaliyopangwa",
  "Refer a neighbour": "Mlete jirani",
  "Referral code": "Msimbo wa rufaa",
  "Referral code (optional)": "Msimbo wa rufaa (si lazima)",
  "Referrals": "Rufaa",
  "Referred by": "Aliletwa na",
  "Relocation": "Kuhamisha",
  "Removal": "Kuondoa",
  "Removed router": "Ruta iliyoondolewa",
  "Repair": "Marekebisho",
  "Reward": "Zawadi",
  "Reward customers who refer a neighbour": "Zawadia wateja wanaoleta jirani",
  "Rewarded": "Amezawadiwa",
  "Rewards appear here when a referred customer makes their first payment.": "Zawadi huonekana hapa mteja aliyeletwa anapolipa mara ya kwanza.",
  "Rewards given": "Zawadi zilizotolewa",
  "Sales and VAT for one month, in your timezone, for the KRA VAT return.": "Mauzo na VAT kwa mwezi mmoja, kwa saa za eneo lako, kwa ajili ya ritani ya VAT ya KRA.",
  "Sales before VAT": "Mauzo kabla ya VAT",
  "Sales including VAT": "Mauzo pamoja na VAT",
  "Save": "Hifadhi",
  "Saving…": "Inahifadhi…",
  "Schedule and notify": "Panga na uarifu",
  "Schedule maintenance": "Panga matengenezo",
  "Scheduled": "Imepangwa",
  "Scheduled and past": "Yaliyopangwa na yaliyopita",
  "Scheduled. Customers are texted before it starts and again when it is over.": "Imepangwa. Wateja watatumiwa ujumbe kabla ya kuanza na tena yakiisha.",
  "Search customers": "Tafuta wateja",
  "Search name or phone": "Tafuta jina au simu",
  "Signed by": "Imesainiwa na",
  "Site survey": "Ukaguzi wa eneo",
  "Something went wrong.": "Kuna tatizo limetokea.",
  "Standard VAT rate (%)": "Kiwango cha kawaida cha VAT (%)",
  "Starting…": "Inaanza…",
  "Starts": "Inaanza",
  "Subscribers who used most of their data cap in the last 30 days, and the next plan up. Apply moves them onto it now.": "Wateja waliotumia sehemu kubwa ya kikomo chao cha data siku 30 zilizopita, na mpango unaofuata. Tekeleza huwahamishia sasa hivi.",
  "Suggest when they have used": "Pendekeza wanapokuwa wametumia",
  "Suggested": "Unapendekezwa",
  "Suggestions": "Mapendekezo",
  "Take or add photos": "Piga au ongeza picha",
  "Technician": "Fundi",
  "Tell customers before you work on the network. They get an SMS before it starts and another when it is over.": "Waambie wateja kabla ya kufanya kazi kwenye mtandao. Hupata SMS kabla ya kuanza na nyingine yakiisha.",
  "Text customers": "Tuma ujumbe kwa wateja",
  "Text the customer about the bigger plan": "Mtumie mteja ujumbe kuhusu mpango mkubwa",
  "Texted": "Wametumiwa ujumbe",
  "The system checks every 6 hours for subscribers near their data cap.": "Mfumo hukagua kila saa 6 kwa wateja walio karibu na kikomo chao cha data.",
  "Their code": "Msimbo wake",
  "They get a push alert if they turned alerts on.": "Hupata arifa kama wamewasha arifa.",
  "They get a reward when someone they referred makes a first payment.": "Hupata zawadi mtu waliyemleta anapolipa mara ya kwanza.",
  "To do": "Za kufanya",
  "To review": "Za kukagua",
  "Total": "Jumla",
  "Uploading…": "Inapakia…",
  "Used in 30 days": "Iliyotumika siku 30",
  "VAT": "VAT",
  "VAT details": "Maelezo ya VAT",
  "VAT inside": "VAT iliyomo",
  "VAT report": "Ripoti ya VAT",
  "Waiting for first payment": "Anasubiri malipo ya kwanza",
  "We are registered for VAT": "Tumesajiliwa kwa VAT",
  "What is happening": "Kinachofanyika",
  "What needs doing": "Kinachohitaji kufanywa",
  "What was done": "Kilichofanyika",
  "When": "Lini",
  "Where and who": "Wapi na nani",
  "Who is affected": "Nani ataathirika",
  "Whose": "Za nani",
  "You are not marked as VAT-registered, so hotspot sales show no VAT. Set your VAT details below if you are registered.": "Hujawekwa kama umesajiliwa kwa VAT, hivyo mauzo ya hotspot hayaonyeshi VAT. Weka maelezo yako ya VAT hapa chini kama umesajiliwa.",
  "e.g. Install fibre and ONT": "mf. Funga fibre na ONT",
  "e.g. Kasarani, next to Seasons Mall": "mf. Kasarani, karibu na Seasons Mall",
  "e.g. ONT HWTC89A120FC, 30 m drop cable": "mf. ONT HWTC89A120FC, kebo ya mita 30",
  "e.g. Replacing the Kasarani tower radio": "mf. Kubadilisha redio ya mnara wa Kasarani",
  "e.g. We are upgrading to faster fibre.": "mf. Tunaboresha hadi fibre yenye kasi zaidi.",
  "earned": "amepata",
  "free days": "siku za bure",
  "invoices": "ankara",
  "invoices issued this month": "ankara zilizotolewa mwezi huu",
  "invoices this month carry no VAT. Set a tax rate on your internet plans so new invoices include it.": "ankara za mwezi huu hazina VAT. Weka kiwango cha kodi kwenye mipango yako ya intaneti ili ankara mpya ziijumuishe.",
  "moved to": "amehamishiwa",
  "sales": "mauzo",
};
